# Gearfetting yn Frysk {-}

**Seksje I**

Wêr is mikrobiale epidemiology begûn? Hoe is it ûntstien? En hoe kin it bydrage oan de holistyske oanpak fan ynfeksjebehear? Dy fragen wurde beäntwurde yn dizze earste seksje. Dêrnei wurdt sketst hokker wichtige hjoeddeistige beheiningen besteane yn ‘e tapassing fan mikrobiale epidemiology yn ‘e praktyk en hoe’t dy oerwûn wurde kinne.

Yn ‘e algemiene ynlieding wurdt yn **haadstik 1** sketst dat mikrobiale epidemiology diel útmakket fan ynfeksjesykte-epidemiology, dy’t op syn beurt ûnderdiel is fan klinyske mikrobiology. Under oaren kin mikrobiale epidemyology sjoen wurde as it wittenskiplike fjild foar it krijen fan nije ynsjoggen oer de ferdieling fan mikro-organismen en harren ûnderskate patroanen yn antymikrobiale resistinsje (AMR). Foarútgong yn ynformaasjetechnology hat ús net allinich de mooglikheden brocht om oer regionale, nasjonale en ynternasjonale grinzen hinne te sjen om ynsicht te krijen yn ‘e fersprieding fan mikro-organismen en AMR, mar sels ek om pandemys yn real-time wier te nimmen, te analysearjen en te begripen. Metoaden dy’t wy hjoed ûntwikkelje en brûke, kinne moarn oan ‘e oare kant fan ‘e wrâld tapast wurde. Dat is in wichtich foardiel yn moderne mikrobiale epidemiology, dêr’t de klam hieltyd mear op data komt te lizzen.

De data dy’t brûkt wyrde as ynput foar mikrobiale epidemiologyske analyzes, wurde faaks ferkrigen út laboratoariumynformaasjesystemen (LIS). Dizze data binne routine-diagnostyske resultaten fan laboratoariumtests. Yn **haadstik 2** is de eigensinnige opfetting oanfierd dat diagnostyk liedt ta rûge resultaten, mar net needsaaklikerwiis ta in direkt antwurd op de klinyske fraach dy’t in behanneljend arts fan in pasjint hawwe kin. Antwurden oan dokters fereaskje in oanpak fan in multydissiplinêr, ferweve “stewardship”-konsept mei in fokus op diagnostyk. Dat fereasket fan medyske spesjalisten yn ‘t algemien (en artsen-mikrobiolooch yn it bysûnder) in nauwe ynteraksje mei kollega’s, sadat dat soarget foar optimale kwaliteit fan soarch en feiligens fan pasjinten; dat is it saneamde Diagnostic Stewardship Program (DSP). De term “stewardship” (rintmasterskip) wurdt breed brûkt om kommunikaasje en klinyske beslútfoarming te fasilitearjen, mar it fêststellen fan in dúdlike definysje fan “stewardship” hat in útdaging bewiisd. Boppedat giet de diagnostyk yn medysk-mikrobiologyske laboratoaria op it stuit fluch foarút mei betrekking ta ferbettere workflows en nije technologyen, lykas matrix-assisted laser desorption/ionisation time-of-flight (MALDI-TOF) massaspektrometry. Dochs is diagnostyk yn ynfeksjebehear breder as dit en omfettet it in protte klinyske gebieten wêr’t kommunikaasje en ynteraksje fûneminteel binne om it bêste gebrûk te meitsjen fan kennis en saakkundigens, sadat alle spesjalismen in bydrage leverje kinne oan pasjintesoarch. De juste test op de juste tiid foar de juste pasjint om de juste fragen te beäntwurdzjen en mei de juste behanneling te begjinnen − dêr giet DSP yn medyske mikrobiology oer. Mikrobiale epidemiology kin brûkt wurde foar in lyts aspekt fan dat diagnostyske gehiel, troch de testresultaten te resirkulearjen om dêrnei ferriking oan te bringen yn it antwurd- generearjende proses dat DSP is.

**Haadstik 3** giet fierder mei it beljochtsjen fan wichtige hjoeddeistige beheiningen by it tapassen fan mikrobiale epidemiology, benammen AMR-analyze. AMR-analyze moat útfierd wurde op in klinysk en epidemiologysk sinfolle manier, mar it is útdaagjend om’t it ekspertize fereasket yn sawol (klinyske) epidemiology as (medyske) mikrobiology, en derneist de juste instruminten om de AMR-analyzes út te fieren. Dit wurdt nochris fierder yngewikkeld troch it ûntbrekken fan de tagonklikens fan LIS-data, om’t de measte LIS-en net ûntwurpen binne mei epidemiologyske analyzes yn ‘e holle. Elk LIS ûnderhâldt bygelyks syn eigen taksonomyske gegevens en laboratoaria binne sels ferantwurdlik foar it regelmjittich bywurkjen dêrfan. Sûnt AMR-rjochtlinen bot basearre binne op de mikrobiale taksonomy (guon regels jilde allinnich foar in spesifyk skaai, oare regels jilde foar in spesifike famylje), moat dizze ynformaasje akkuraat wêze en by de tiid. Spitigernôch is troch ûndersyk ûnder sân medysk-mikrobiologyske laboratoaria yn Nederlân bliken dien dat al harren LIS-en tige ferâldere taksonomyske nammen befetsje. Dit kin slimme gefolgen hawwe foar sawol de routinerapportaazje fan resultaten as foar (takomstige) epidemyologyske analyzes. Om dy redenen waard yn dit haadstik it AMR-pakket foar R yntrodusearre as in nij epidemiologysk ynstrumint foar AMR-analyze dat fergees, ûnôfhinklik, open-source en iepenbier beskikber is. It waard ûntwikkele troch in team fan tolve ferskillende iepenbiere soarchorganisaasjes út sân ferskillende lannen en biedt help om it opskjinjen, transfomearjen en analysearjen fan AMR-gegevens te ferienfâldigjen, en biedt tagelyk metoaden om maklik (ynter)nasjonale rjochtlinen en wittenskiplik betroubere referinsjegegevens ta te passen. Tsjin maaie 2021 wie it mear as 50.000 kear ynladen troch brûkers út 162 ferskillende lannen sûnt de earste release yn 2018. De resultaten fan in enkête ûnder brûkers presintearre yn dit haadstik, litte sjen dat it gebrûk liedt ta mear reprodusearberens fan analyzeresultaten, betrouberdere resultaten fan AMR-analyzes, en sawol nije as ferbettere ynsjoggen yn AMR foar de ynstellings en regio’s fan ‘e brûkers. Brûkers stelden ek dat it AMR-pakket brûkt wie om klinyske beslútfoarming te stypjen. It pakket lost it ûngemak op fan it ôfhinklik wêzen fan (ynter)nasjonale rjochtlinen en betroubere (referinsje)gegevens, wylst it ek in wiidweidige ‘toolbox’ biedt foar de analyze sels. It AMR-pakket foar R kin dêrom in help wêze foar elke spesjalist yn it fjild dy’t mei AMR-gegevens wurket.

**Seksje II**

Nei de útdagings dy’t sketst binne yn ‘e foarige seksje, wurdt yn dizze seksje it AMR-pakket foar R beskreaun as in nij ynstrumint om dy útdagingen oan te pakken. Fanút ferskate perspektiven wurdt it AMR-pakket en syn foardielen beljochte: fanút in technysk perspektyf, fanút it perspektyf fan ynfeksjebehear en fanút in klinysk perspektyf. Dy kombinaasje jout in mienskiplike basis foar it begripen fan de oplossingen dy’t it AMR-pakket biede kin en hoe’t it in nij begjinpunt foarmje kin foar takomstige tapassingen fan mikrobiale epidemiology.

De technyske skaaimerken fan it AMR-pakket foar R wurde beskreaun yn **haadstik 4**, dêr’t yn beskreaun wurdt hoe’t it AMR-pakket ûntwurpen is om reprodusearbere AMR-analyzes te standerdisearjen oan ‘e hân fan ynternasjonale standert oanrikkemedaasjes. Om dat mooglik te meitsjen, wurde wittenskiplik betroubere referinsjegegevens brûkt foar de falidaasje fan laboratoariumresultaten, antymikrobiale middels en de folsleine biologyske taksonomy fan mikro-organismen. Boarnegegevens moatte analysearre wurde yn de meast betroubere wei, foaral wannear’t it resultaat, bygelyks, brûkt wurde sil om de behannelopsjes foar in psjint te evaluearjen. Dit freget reprodusearbere en spesjalisearre ferwurking fan gegevens. It AMR-pakket biedt in standerdisearre en automatisearre manier om mienskiplike LIS-data op te skjinjen, te transformearjen en te ferbetterjen, ûnôfhinklik fan de ûnderlizzende databoarne en de krektens fan ‘e data. Foar dit doel, binne algemien tapasbere algoritmen ûntwikkele, om AMR-testresultaten opskinje te kinnen en nammen fan mikro-organismen en antymikrobiale middels falidearje te kinnen. De formule foar de falidaasje fan taksonomyske nammen hâldt rekken mei it foarkommen fan siikmeitsjende mikro-organismen en is kontekstbewust oangeande oare taksonomyske skaaimerken sa as it keninkryk, fylum, oarder en famylje. Bygelyks wurdt de wearde “E. coli” oersetten nei de baktearje Escherichia coli, wylst de brûker ek ynformeare wurdt dat de parasyt Entamoeba coli ek in mooglikheid is, mar in legere kâns hat. Mei help fan handige funksjes kinne brûkers fluch konsistinte mikrobiale eigenskippen weromfine, lykas it taksonomyske keninkryk, famylje, skaai, soarte, ferâldere taksonomyske nammen en sels de Gram-kleur. Neist ynformaasje oer mikro-organismen, befettet it pakket ek referinsjegegevens oangeande antibiotika, wêrûnder in protte foarkommende LIS-koades, offisjele nammen, ATC-koades (Anatomical Therapeutic Chemical), definearre deistiche doses (defined daily doses, DDD), en mear as 5.000 hannelsnammen fan 456 antymikrobiale middels. Mei dizze referinsjegegevens kinne brûkers rauwe gegevens oersette en eigenskippen weromfine oer elk mikro-organisme of antibiotikum. Boppedat is it AMR-pakket yn steat om multiresistinte organismen (multidrug-resistant organisms, MDRO’s) te identifisearjen basearre op nasjonale en ynternasjonale rjochtlinen, minimum inhibitory concentrations (MIC’s) te ynterpretearjen, en kin it de earste isolaten bepale dy’t brûkt wurde moatte foar it berekkenjen fan AMR foar sawol monoterapy as kombinaasje-terapyen. It AMR-pakket is bedoeld om in breed helpmiddel te wêzen foar data-technysk personiel dat wurket yn it gebiet fan AMR, hoewol’t it gebrûk net beheind is ta dy groep.

As yllustraasje hjirfan wurdt yn **haadstik 5** sjen litten dat it AMR-pakket likernôch brûkt wurde kin as in soarte fan rêchbonke yn in ynteraktive open-source software-applikaasje foar ynfeksjemangement en antimicrobial stewardship, neamd RadaR (rapid analysis of diagnostic and antimicrobial patterns in R). Ynfeksjemangement yn ‘e foarm fan Antimicrobial Stewardship Programma’s (ASP), hat him ûntpopt as in effektive oplossing om it globale sûnensprobleem fan antibioatikaresistinsje yn sikehuzen oan te pakken. Dit is yn oerienstimming mei **haadstik 2**; stewarship-yntervinsjes en -aktiviteiten rjochtsje harren op yndividuele pasjinten (persoanlike genêskunde en konsultatie), mar likegoed op pasjintgroepen of klinyske syndromen, dêr’t elke yntervinsje liede moat ta ferbettering fan de kwaliteit fan ‘e soarch en de feiligens fan de pasjint. It is lykwols dreech om pasjintgroepen yn ‘e deistige praktyk te analysearjen (bgl. stratifisearre nei ôfdieling, spesifike antymikrobiale middels, of brûkte diagnostyske prosedueres). It is sels noch lestiger om fluch grutte pasjintpopulaasjes te analysearjen (bgl. ferspraat oer meardere spesjaliteiten), ek al is dizze ynformaasje beskiber yn ‘e data. Dêrom wie de ûntwikkeling fan RadaR bedoeld om ASP-teams te foarsjen fan in brûkersfreonlik en tiidsbesparjend ynstrumint, sûnder dat de djippe technyske ekspertize nedich is. RadaR biedt ûnder oaren Kaplan-Meier -curves oer de lisduur yn sikehuzen, tiidtrends foar it oantal opnames, antibiotikagebrûk, en in automatisearre AMR-data-analyze dêr't it AMR-pakket foar R foar brûkt is. RadaR is falidearre troch 12 ESGAP-leden (European Society of Clinical Microbiology and Infectious Diseases Study Group for Antimicrobial Stewardship) út 9 ferskillende lannen. It hat it potinsjeel in tige brûkber ynstrumint te wêzen yn ‘e deistige praktyk fan sawol ynfeksjebehear as ASP-teams. Dêrnjonken waard yn dit haadstik dúdlik dat it AMR-pakket brûkt wurde kin as ûnderdiel fan in oare software-oplossing om yntegrearre ynfeksjebehear mooglik te meitsjen.

Dêrút folgjend yllustrearret **haadstik 6** de effektiviteit fan it AMR-pakket ûnder brûkers, troch it beoardieljen fan de brûkberens en it effekt op de wurkstream fan dokters yn in typysk klinysk senario. Hoewol’t it AMR-pakket yn wittenskiplik ûndersyk al yn ferskate stúdzjes út ferskate lannen brûkt is, wie der noch gjin analyze fan ‘e ynfloed op AMR-analyze en -rapportaazje yn in klinyske omjouwing. De analyze en rapportaazje fan AMR-data fereaskje spitigernôch spesjaal oplaat personiel. Derneist kinne AMR-data-analyzes tiidsrôvjend wêze. Om de impact hjirfan yn in klinyske omjouwing te beoardieljen, waarden algemiene ûndersyksfragen oer bloedkultuerdata gearstald dy’t troch klinysk routinepersoniel beäntwurde wurde moasten, wêrûnder artsen-mikrobiolooch, bernedokters en yntinsivisten. Yn totaal diene tsien klinici mei oan ‘e stúdzje. Boppedat waard dielnimmers frege in online fragelist yn te foljen oer har eftergrûn, demografy (lykas leeftyd en geslacht), en eardere ûnderfining mei software en AMR-data-analyze en -rapportaazje. Alle dielnimmers moasten de fragen twa kear beäntwurdzje: de earste kear mei de software fan harren eigen kar (earste ronde) en de twadde kear mei in nij ûntwikkele webapplikaasje, boud om it AMR-pakket foar R hinne (twadde ronde). In effisjinte agile workflow waard brûkt foar de ûntwikkeling fan dizze webapplikaasje. De antwurden op de ûndersyksfragen tsjinnen as basis om de effektiviteit (antwurden op elke taak foar elke brûker) en de effisjinsje (tiid bestege oan it oplossen fan elke taak) te fergelykjen tusken de twa rondes. Net alle dielnimmers koene taken binnen it foarskreaune tiidsbestek foltôgje. De gemiddelde foltôging per taak tusken de earste en twadde ronde naam ta fan 56% nei 96% en it persintaazje goede antwurden wie tanommen fan 38% nei 98%. De gemiddelde tiid per ronde waard fermindere mei mear as in oere. Dit haadstik toant dêrmei  de ferhege effektiviteit, effisjinsje en krektens fan it brûken fan it AMR-pakket foar R foar AMR-analyze yn ferliking mei tradisjonele software lykas Microsoft Excel en SPSS.

**Seksje III**

In protte klinyske stúdzjes op it gebiet fan ynfeksjesykten en medyske mikrobiology binne ôfhinklik fan ien of oare foarm fan (mikrobiale) epidemiology. Wylst yn ‘e foarige seksje it AMR-pakket yntrodusearre waard en it gebrûk yn ferskate senario’s ûndersocht waard, begjint dizze seksje mei in epidemiologysk ûndersyksprojekt yn ‘e Noard-Nederlânske regio, en wreidet dizze seksje dêrnei út nei de Nederlânsk-Dútske grinsregio om de distribúsje, it foarkommen en de AMR fan ferskate sykteferwekkende mikro-organismen op in (je)regionaal nivo better begripe te kinnen. Troch yn te zoomen op de regio’s oan beide kanten fan in lânsgrins, kinne op mikronivo ferlikings makke wurde tusken twa ferskillende naasjes. En ferskillende naasjes betsjut úteinlik ferskillende soarchstruktueren. Wat bliuwt oer fan ‘One Health‘? Wat binne de konsekwinsjes fan it hawwen fan ferskillen tusken lannen yn testtechniken, antibiotika-ynterpretaasjes en mikrobiologysk screeningsbelied? Dizze seksje jout antwurden op dy fragen.

**Haadstik 7** rjochtet him op koägulaze-negative stafylokokken (KNS),  wêrfan’t bekend is dat se bloedstreamynfeksjes (BSY) en hege mortaliteit feroarsaakje kinne, hoewol’t se jierrenlang mar as ‘gewoan’ kontaminaasje beskôge waarden. Boppedat wurde KNS-en hieltyd faker assosjeare mei nosokomiale ynfeksjes. Op it stuit bestiet de KNS-groep út 45 ferskillende soarten (‘species’), hoewol it bepalen fan it soartnivo pas koartlyn mooglik makke is foar routine-diagnostyske laboratoaria. Sûnt 2012 is nammentlik MALDI-TOF massaspektrometry de standert foar de identifikaasje fan bakteriële soarten lykas KNS. Hjirfoar waard de ydentifikaasje benammen dien mei biogemyske en fysiologyske testmetoaden, dy’t fariearjende resultaten opleveren, yn it bysûnder by minder foarkommende soarten. AMR, en yn it bysûnder multyresistinsje, is in tanimmend probleem yn KNS-en. Dochs wurde KNS-en yn behannelrjochtlinen en nasjonale tafersjochprogramma’s (lykas it Nederlânske NethMap), noch hieltyd as ien groep sjoen, sûnder differinsjaasje tusken soarten. Om dizze reden is net folle bekend oer trends yn it foarkommen fan, en AMR yn, KNS-en op lokaal en regionaal nivo. Dêrom toant dizze retrospektive stúdzje in detaillearre AMR-analyze fan hast 20 tûzen KNS-isolaten dy't fûn wiene yn alle beskikbere 70 tûzen bloedkultuerisolaten tusken 2013 en 2019 yn Noard-Nederlân. Mei dizze analyze hawwe wy stribbe om ferskillen yn it foarkommen fan KNS-soarten en harren AMR-patroanen te evaluearjen en om harren klinyske mikrobiologyske relevânsje te beoardieljen. Yn totaal waarden 27 ferskillende soarten fan ‘e KNS-groep fûn. Grutte ferskillen waarden sjoen yn it foarkommen fan ‘e ferskillende soarten: de top fiif bestie út 97% fan alle isolaten (S. epidermidis, S. hominis, S. capitis, S. haemolyticus en S. warneri). It oanpart fan KNS-en op ‘e intensive care (IC) neffens oare ôfdielings wie signifikant ferskillend tusken perifeare sikehuzen en it universitêr sikehûs. Om’t net bekend wie hokker pasjinten in BSY hienen, waard “KNS-persistinsje” definieare as in surrogaat wêrfoar teminsten trije positive bloedkulturen nommen wurde moasten op trije ferskillende dagen, binnen 60 dagen, wêr’t deselde KNS yn fûn wie, by deselde pasjint. De relatyf meast foarkommende oarsaaklike ferwekker fan KNS-persistinsje wie S. haemolyticus, folge troch S. epidermidis en S. lugdunensis. AMR-analyze hat wichtige ferskillen iepenbiere tusken de KNS- soarten. Bygelyks eksposearren S. epidermidis en S. haemolyticus 50% oant 80% resistinsje tsjin de measte antibiotika, wylst de resistinsje tsjin dizze middels by ‘e measte oare KNS-en leger as 10% bleau. En dochs op nasjonaal nivo, lykas yn NethMap, wurde dizze ferskillen ferwaarleazge, wat liede kin ta de ûntwikkeling fan behannelrjochtlinen dy’t har rjochtsje op feilige en fertroude middels foar de behanneling fan KNS, lykas vancomycine of linezolid. Middels lykas tetracycline, cotrimoxazol, en erythromycine soenen as alternative opsjes beskôge wurde kinne foar guon soarten, wêr't de AMR, neffens ús ûndersyksresultaten, nea boppe de 10% útkaam is. Ta beslút kin steld wurde dat in mearjierrige regio-oerstiigjende oanpak tapast is om de ûntwikkelingen yn sawol it foarkommen as de antibioatikaresistinsje fan LNS-soarten wiidweidich te beskôgjen, om sadwaande it behannelbelied te evaluearjen en mear te begripen oer dizze wichtige, mar noch net faak genôch serieus nommen sykteferwekkers. Dêrneist tsjinne dizze stúdzje as in praktysk foarbyld fan hoe’t it AMR-pakket foar R brûkt wurde kin yn stúdzjes om nije ynsjoggen te krijen oer antibiotikaresistinsje mei epidemiologysk ûnderboude metoaden.

Nei oanlieding fan de nije befinings troch it bestudearjen fan AMR-testresultaten yn Noard-Nederlân, jout **haadstik 8** in ferliking fan nasjonale ynterpretaasjes fan MDRO’s yn de Nederlânsk-Dútske grinsregio, benammen oangeande de praktyske gefolgen foar personiel yn de sûnenssoarch dy’t ticht by de grins wurkje. It fergelykjen fan AMR yn it algemien, net allinne MDRO’s, yn dizze grinsregio is tige ynteressant om’t beide lannen karakterisearre wurde troch heech ûntwikkele, mar dochs struktureel oars ynrjochte soarchsystemen. Antibioatika-ynterpretaasjes fan pasjinten wurde oerdroegen tusken soarchynstellings yn dizze twa lannen, wylst de ûnderlizzende definysjes ferskille. Dêrtroch moatte dokters en ynfeksjeprevinsje-meiwurkers de antibioatikaresultaten fan beide kanten fan ‘e grins begripe kinne en yn steat wêze beide nasjonale MDRO-rjochtlinen tapasse te kinnen. Troch antibiogrammen fan Gram-negative baktearjes fan beide kanten fan ‘e grins mei-inoar te fergelykjen, waard besocht de omfang fan ynfloed fan dizze útdagingen te bepalen. Dêrta waarden tusken 2015 en 2016 35.619 antibiogrammen út seis Nederlânske en fjouwer Dútske sikehûzen analysearre foar alle soarten Enterobacteriaceae, en P. aeruginosa, it A. baumannii-kompleks en Stenotrophomonas maltophilia. Foar al dizze soarten besteane yn dizze regio MDRO-oanbefellings en spesjale ynfeksjeprevinsjemaatrigels. Út de Nederlânske sikehûzen waarden 12.616 antibiogrammen selekteare mei it AMR-pakket foar R, wêrmei ek de Nederlânske MDRO-rjochtline tapast wurde koe. Wichtich is dat oare nasjonale en ynternasjonale rjochtlinen, lykas de Dútske MDRO-rjochtline, ek opnommen binne yn it AMR-pakket foar R. Út Dútske sikehûzen waarden 23.003 antibiogrammen selekteare. Neffens de Nederlânske rjochtline wie 24,5% fan alle isolaten in MDRO. Neffens de Dútske rjochtline wie 12,9% fan alle isolaten in MDRO. Lykwols waard 73,7% fan alle isolaten net klassifisearre as in MDRO neffens ien fan ‘e beide rjochtlinen. By it oerdragen fan pasjinten tusken sikehûzen, moat ek ynformaasje oer MDRO-kolonisaasje of -ynfeksje oerdroegen wurde om de trochgeande útfiering fan ynfeksjeprevinsjemaatrigels te garandearjen. Foar regio-oerstiigjende sûnenssoarch betsjut dit dat klinici en ynfeksjeprevinsjemeiwurkers yn steat wêze moatte om MDRO’s te bepalen basearre op antibiogrammen neffens de rjochtlinen fan ien fan beide lannen. Foar regio-oerstiigjende sûnenssoarch soe dêrom de ienfâldichste oplossing wêze om de rjochtlinen fan beide lannen te harmonisearjen. Dat soe ek de begryplike betizing oplosse kinne dy’t pasjinten ûnderfine kinne as ynfeksjeprevinsjemaatrigels oplein wurde yn it iene lân, mar opheft wurde nei oerdracht nei it oare lân. Oant de harmonisaasje berikt is, soenen de folsleine AMR-gegevens tegearre mei de pasjint oerdroegen wurde moatte om’t klassifikaasje foar lokale ynfeksjeprevinsje-meiwurkers mooglik te meitsjen.

Oare AMR-relatearre grinsoerstiigjende útdagings en ferskillen wurde yllustrearre yn **haadstik 9**, dat in wiidweidige mikrobiale epidemiologyske analyze omfettet fan it foarkommen fan MRSA, it belied en de ynfloed op sûnenssoarch yn ‘e Nederlânsk-Dútske grinsregio. MRSA is noch altyd ien fan ‘e liedende oarsaken fan sikehûs-relatearre ynfeksjes troch resistinte baktearjes. Yn dizze stúdzje waarden MRSA-tafersjochgegevens fan fiif jier (2012-2016) út Nederlânske en Dútske sikehuzen yn ‘e grinsregio analysearre om regio-spesifike trends oer tiid fan MRSA beskriuwe te kinnen en om ferskillen tusken sikehûsgroepen fêst te stellen. De stúdzje omfette 42 sikehûzen yn ‘e Nederlânsk-Dútske grinsregio mei sawat 620.000 opnommen pasjinten (68,0% yn it Dútske diel fan ’e ûndersyksregio) mei hast fjouwer miljoen pasjintdagen per jier. Alle sikehuzen hiene MRSA-relatearre previnsjemaatrigels ymplementeare neffens harren nasjonale rjochtlinen en oanbefellings, en ferskillen yn rjochtlinen tusken de twa lannen waarden fergelike. Oan beide kanten fan ‘e grins naam it MRSA-screeningspersintaazje tusken 2012 en 2016 bot ta, hoewol de MRSA-ynsidinsje oer de tiid stabyl bleau oan beide kanten fan ‘e grins. Yn totaal wie it screeningspersintaazje yn ‘e Dútske grinsregio 14 kear heger as yn ’e Nederlânske grinsregio. It persintaazje MRSA yn bloedkultuerisolaten mei S. aureus sakke fan 13% yn 2012 nei 5% yn 2016 yn ‘e Dútske grinsregio, wylst it stabyl bleau yn ‘e Nederlânske grinsregio (0% oant 2%). Dochs wie MRSA ûnder S. aureus-isolaten 34 kear heger yn ‘e Dútske grinsregio. De listiid yn it sikehûs by MRSA-pasjinten wie yn beide regio’s lyksoartich, wylst de algemiene listiid flink fariearre. Fierder wie it oantal MRSA-útstriken foar of by sikehûsopname per 100 ynwenners 12,2 yn ‘e Dútske grinsregio en 0,36 yn ‘e Nederlânske grinsregio; 34 kear heger yn ‘e Dútske grinsregio. It oantal yntramurale MRSA-gefallen per 1.000 ynwenners wie 2,52 yn ‘e Dútske grinsregio en 0,14 yn ‘e Nederlânske grinsregio. Dizze stúdzje toande dus signifikante ferskillen oan tusken Nederlânske en Dútske sikehûzen. De MRSA-ynsidinsje yn Dútske sikehûzen wie mear as sân kear heger as yn Nederlânske sikehûzen. Neffens it European Centre of Disease Prevention and Control (ECDC) wurde ferskillen yn it foarkommen fan resistente sykteferwekkers tusken Jeropeeske lannen wierskynlik feroarsake troch ferskillen yn soarchgebrûk, antimykrobieel gebrûk en ynfeksjeprevinsjemaatrigels. Wat it soarchgebrûk yn ús kontekst oanbelanget, fûnen wy dat ynwenners yn it Dútske diel fan ‘e stúdzje hast trije kear sa faak yn it sikehûs opnommen wiene en in tige langere listiid hiene as pasjinten yn it Nederlânske diel. Dit kin wêze troch sosjaal-ekonomyske faktoaren of in oare ynrjochting fan ambulante sûnenssoarch. Dizze wiidweidige stúdzje oer MRSA yn sikehûzen rûn in Jeropeeske grins hat sjen litten dat trochgeand MRSA-tafersjoch nuttich wêze kin om trends fan MRSA te folgjen, om (ynter)nasjonale fergelikingen ta te stean.

De diskusje fan dizze stúdzje waard ôfsletten mei (oersetten) “grinsoerstiigjend tafersjoch soe útwreide wurde moatte nei oare multyresistinte mikro-organismen”, wat krekt is wêr’t **haadstik 10** op trochgiet. Sûnt net allinne MRSA’s mar MDRO’s yn it algemien in risiko posearje foar de sûnenssoarch, sawol yn ‘e mienskip as yn de sikehuzen, hie dizze stúdzje ta doel om it foarkommen fan meardere MDRO’s yn dizze grinsregio fêst te stellen om sadwaande verskillen better begripe te kinnen, en om ynfeksjeprevinsje te ferbetterjen, baseare op real-time routinegegevens. Foar dat doel namen 23 sikehûzen yn ‘e Nederlânsk-Dútske grinsregio tusken 2017 en 2018 diel oan dizze prospective stúdzje troch alle pasjinten op tagong ta de intensive care (IC) te ûndersykjen. Alle sikehûzen (8 yn ‘e Nederlânske grinsregio, 15 yn ‘e Dútske grinsregio) dienen elk mei foar acht opienfolgjende wiken en ûndersochten yn dy perioade pasjinten foar dragerskip fan MRSA, vancomycine-resistinte Enterococcus faecium/E. faecalis (VRE), tredde-generaasje cefalosporine-resistinte Enterobacteriaceae (3GCRE) en carbapenem-resistinte Enterobacteriaceae (CRE). Yn totaal waarden 3.365 pasjinten ûndersocht: 35,7% op Nederlânske IC’s en 64,3% op Dútske IC’s. De mediane leeftyd fan alle screenede pasjinten wie 68 jier (IQR: 57-77), wêrby pasjinten yn ‘e Dútske grinsregio signifikant âlder wiene as pasjinten yn ‘e Nederlânske grinsregio. De algemiene screening compliance (screened foar teminsten ien MDRO-groep) wie 60%. Alle AMR-data-analyzes waarden útfierd en automatisearre mei help fan it AMR-pakket foar R. It foarkommen fan MRSA wie 1,7% op Dútske IC’s en 0,6% op Nederlânske IC’s. It foarkommen fan VRE wie 2,7% op Dútske IC’s en 0,1% op Nederlânske IC‘s. Opfallend wie dat dit foarkommen yn it Dútske grinsgebiet útienrûn fan 0% oant 4,1%. Alle 56 gefallen fan VRE waarden feroarsake troch E. faecium. It foarkommen fan 3GCRE wie 6,6% op Dútske IC’s en 3,6% op Nederlânske IC’s, wylst it foarkommen fan CRE oan beide kanten fan de grins tichtby nul bleau. It foarkommen fan Gram-negative MDRO’s ferskilden tusken sikehuzen yn beide lannen, fariearjend fan 0% oant 5,0% yn ‘e Nederlânske grinsregio en fan 1,2% oant 10,9% yn ‘e Dútske grinsregio. Foar de ynbegrepen Nederlandse IC’s wie it foarkommen fan alle MDRO-groepen net gâns oars tusken perifeare sikehuzen en it universitêr sikehûs. Op de Dútske IC’s wie it foarkommen fan Gram-negative MDRO’s lykwols heger yn perifeare sikehuzen. Yn ‘e Nederlânske grinsregio liede 4,8 per 100 sikehûsopnames ta in IC-opname. Yn ‘e Dútske grinsregio wie dit oars 7,7 per 100 sikehûsopnames. Dit ferskil kin ferklearre wurde troch de hegere IC-kapasiteit yn Dútske sikehûzen (4,8% fan alle sikehûsbêden) yn ferliking mei Nederlânske sikehûzen (2,4% fan alle sikehûsbêden). It algehiele foarkommen fan ferskillende MDRO’s wie heger op Dútske IC’s, hoewol’t guon ferskillen tige lyts wiene. Benammen it foarkommen fan MRSA wie trije kear heger yn ‘e Dútske grinsregio as yn ‘e Nederlânske grinsregio, wat konsistint is mei de ûndersyksresultaten yn **haadstik 9**. Dochs wiene de ûndersyksresultaten net konsistint mei (ynter)nasjonale gemiddelden. Bygelyks, it foarkommen fan 3GCRE wie hast twa kear sa heech yn ‘e Dútske grinsregio as yn ‘e Nederlânske grinsregio, mar beide wiene noch hieltyd leger as it nasjonale gemiddelden; de ECDC rapporteare 6% hegere 3GCRE-persintaazjes ûnder E. coli en K. pneumoniae út bloedkulturen foar Dútslân en Nederlân. Dit lit sjen dat der wichtige ferskillen binne tusken it bestudearjen fan dragerskip yn bepaalde populaasjes en it bestudearjen fan it oanpart fan (wierskynlik) invasive isolaten. Dizze stúdzje beklammet dêrom it belang fan in regionale en grinsoerstiigjende oanpak yn in Jeropeeske grinsregio, om it ferskil yn foarkommen fan AMR tusken de regio’s te yllustrearjen en om potinsjele ferskillen mei nasjonale rapporten te beljochtsjen. Om dat fierder út te wurkjen is in djipper nivo fan detail nedich, bygelyks troch ynformaasje te sammeljen oer (ynfeksjeprevinsje) personiel, MDRO-útbraken, ynfeksjes, antibiotikagebrûk en risikofaktoaren fan pasjinten. Yn konklúzje lykje geografyske en politike grinzen troch MDRO’s net “respektearre” te wurden, hoewol sûnenssoarchsystemen, geografyske lokaasje en rjochtlinen ferskille fan lân nei lân. De persintaazjes MDRO’s fan guon sykteferwekkers, lykas nasjonaal en ynternasjonaal rapportearre, reflektearje net it foarkommen fan MDRO’s yn in pasjint en/of yn ‘e algemiene befolking. Dat moat yn alle earnst beskôge wurde by it ynterpretearjen fan rapporten op nasjonaal of sels kontinintaal nivo.

**Konklúzje**

Fanút ferskate perspektiven wurdt it AMR-pakket en syn foardielen beljochte: fanút in technysk perspektyf, fanút it perspektyf fan ynfeksjebehear en fanút in klinysk perspektyf. Dy kombinaasje jout in mienskiplike basis foar it begripen fan de oplossingen dy’t it AMR-pakket biede kin en hoe’t it in nij begjinpunt foarmje kin foar takomstige tapassingen fan mikrobiale epidemiology, sawol yn klinyske omjouwings as yn wittenskiplik ûndersyk. Dit proefskrift giet yn op dizze perspektiven troch it gebrûk fan dit nije ynstrumint te yllustrearjen  yn epidemiologyske stúdzjes yn ‘e Nederlânsk-Dútske grinsregio om de distribúsje, it foarkommen en de AMR fan ferskate sykteferwekkende mikro-organismen op in (je)regionaal nivo better begripe te kinnen. Ta beslút toant dit proefskrift de tafoege wearde fan in konsekwint data-analytysk ynstrumint om AMR-data foar te meitsjen en te analysearjen yn in regio-oerstiigjende oanpak, om nije ynsjoggen te krijen yn AMR-trends.
