# Samenvatting in het Nederlands {-}

**Sectie I**

Waar is de microbiële epidemiologie begonnen? Hoe is het ontstaan? En hoe draagt het bij tot de holistische benadering van infectiemanagement? Deze vragen worden in deze eerste sectie beantwoord. Vervolgens wordt geschetst welke belangrijke huidige beperkingen er bestaan bij de toepassing van microbiële epidemiologie in de praktijk en hoe deze zouden kunnen worden ondervangen.

In de algemene inleiding in **hoofdstuk 1** van dit proefschrift wordt geschetst dat microbiële epidemiologie een onderdeel is van de epidemiologie van infectieziekten, die op haar beurt weer een onderdeel is van de medische microbiologie. Microbiële epidemiologie kan onder andere worden gezien als het wetenschappelijke veld voor het verwerven van nieuwe inzichten over de verspreiding van micro-organismen en hun respectievelijke antimicrobiële resistentie (AMR). De vooruitgang in de informatietechnologie heeft ons niet alleen de mogelijkheden gebracht om over regionale, nationale en internationale grenzen heen te kijken om inzicht te krijgen in de verspreiding van micro-organismen en AMR, maar zelfs om pandemieën real-time te analyseren en te begrijpen. Methoden die we vandaag ontwikkelen en gebruiken, kunnen bij wijze van spreken morgen aan de andere kant van de wereld worden toegepast. Dit is een belangrijk voordeel van moderne microbiële epidemiologie, waarin de focus steeds meer op data komt te liggen.

De data die als input voor microbieel epidemiologische analyses worden gebruikt, worden vaak verkregen uit laboratoriuminformatiesystemen (LIS). Deze data bestaan uit routine-diagnostische resultaten van laboratoriumtests. In **hoofdstuk 2** wordt de mening naar voren gebracht dat diagnostiek wél kan leiden tot ruwe resultaten, maar níet noodzakelijkerwijs leidt tot een direct antwoord op de klinische vraag die een behandelend arts van een patiënt kan hebben. Om artsen van antwoorden te voorzien is de aanpak van een multidisciplinair, verweven “stewardship”-concept nodig met een focus op diagnostiek. Dit vraagt van medisch specialisten in het algemeen (en artsen-microbioloog in het bijzonder) een nauwe interactie voor optimale kwaliteit van zorg en patiëntveiligheid dat leidt tot succesvol infectiemanagement: diagnostisch stewardship (DSP). Het begrip “stewardship” wordt veel gebruikt om communicatie en klinische besluitvorming te vergemakkelijken, maar het is een uitdaging gebleken om een duidelijke definitie van “stewardship” vast te stellen. Bovendien boekt de diagnostiek in medisch microbiologische laboratoria momenteel snelle vooruitgang met betrekking tot verbeterde workflows en nieuwe technologieën, zoals matrix-assisted laser desorption/ionisation time-of-flight (MALDI-TOF) massaspectrometrie. Diagnostiek bij infectiemanagement is echter breder dan dit en bestrijkt veel klinische gebieden waar communicatie en onderlinge interactie van fundamenteel belang zijn om optimaal gebruik te kunnen maken van kennis en expertise, zodat alle specialismen een bijdrage kunnen leveren aan patiëntenzorg. De juiste test op het juiste moment voor de juiste patiënt om de juiste vragen te beantwoorden en de juiste behandeling te starten – dat is waar het bij DSP in de medische microbiologie om draait. Microbiële epidemiologie kan ingezet worden voor een klein aspect van het diagnostische geheel, door testresultaten te recyclen en vervolgens verrijkingen aan te brengen in het antwoord-genererende proces dat DSP belichaamt.

**Hoofdstuk 3** gaat verder met het belichten van belangrijke huidige beperkingen bij de toepassing van microbiële epidemiologie, in het bijzonder bij de analyse van AMR-data. De analyse van AMR-data moet worden verricht op een klinisch en epidemiologisch zinvolle manier, hoewel dit een uitdaging is door de vereiste expertise in (klinische) epidemiologie en (medische) microbiologie, en goede instrumenten om de AMR-data-analyse uit te voeren. Dit wordt nog eens verder bemoeilijkt door het gebrek aan de toegankelijkheid van LIS-data, aangezien de meeste LIS-en niet zijn ontworpen om epidemiologische analyses te doen. Elk LIS houdt bijvoorbeeld zijn eigen taxonomische gegevens bij en de laboratoria zijn verantwoordelijk voor de regelmatige bijwerking ervan. Aangezien AMR-richtlijnen sterk gebaseerd zijn op de microbiële taxonomie (sommige regels gelden bijv. alleen voor een specifieke genus, andere regels gelden voor een specifieke familie), moet deze informatie correct en up-to-date zijn. Helaas is uit onderzoek onder zeven medisch microbiologische laboratoria in Nederland gebleken dat al hun LIS-en sterk verouderde taxonomische namen bevatten. Dit kan gevolgen hebben voor zowel de routinematige rapportage van resultaten als voor (toekomstige) epidemiologische analyses. Om deze redenen is in dit hoofdstuk het AMR-pakket voor R (een programmeertaal voor statistische berekeningen) geïntroduceerd als een nieuw epidemiologisch instrument voor de analyse van AMR-data. Het AMR-pakket is gratis, onafhankelijk, open-source, en openbaar beschikbaar. Het is ontwikkeld met een team van twaalf verschillende gezondheidsorganisaties in zeven verschillende landen en biedt hulpmiddelen om het opschonen, transformeren en analyseren van AMR-data te vereenvoudigen, mar ook om gemakkelijk (inter)nationale richtlijnen te kunnen toepassen en wetenschappelijk betrouwbare referentiedata te kunnen gebruiken. In mei 2021 was het meer dan 50.000 keer gedownload door 162 verschillende landen sinds de eerste release in 2018. Uit de resultaten van een enquête onder gebruikers die in dit hoofdstuk worden gepresenteerd, blijkt dat het gebruik ervan leidt tot meer reproduceerbaarheid van analyseresultaten, betrouwbaardere uitkomsten van AMR-data-analyses, en nieuwe of verbeterde inzichten in AMR voor de instellingen en regio’s van de gebruikers. Gebruikers gaven ook aan dat het AMR-pakket gebruikt is om klinische besluitvorming te ondersteunen. Het pakket lost het ongemak op van het afhankelijk zijn van (inter)nationale richtlijnen en betrouwbare (referentie)data, terwijl het ook een uitgebreide ‘toolbox’ biedt voor de analyse zelf. Het AMR-pakket voor R kan daarom elke specialist in ons veld die met AMR-gegevens werkt in staat stellen zijn werk makkelijker te doen.

**Sectie II**

Na de uitdagingen die in de vorige sectie zijn geschetst, wordt in deze sectie het AMR-pakket voor R geïntroduceerd als een nieuw instrument om deze uitdagingen aan te gaan. Vanuit verschillende invalshoeken worden het AMR-pakket en zijn voordelen in perspectief geplaatst: vanuit een technisch perspectief, vanuit het perspectief van infectiemanagement en vanuit een klinisch perspectief. Deze combinatie biedt een gemeenschappelijke basis voor het begrijpen van de oplossingen die het AMR-pakket kan bieden en hoe het een nieuw startpunt kan vormen voor toekomstige toepassingen van microbiële epidemiologie.

De technische functionaliteiten van het AMR-pakket voor R zijn beschreven in **hoofdstuk 4**, waarin wordt beschreven hoe het AMR-pakket is ontwikkeld om reproduceerbare AMR-data-analyses te standaardiseren aan de hand van internationale gestandaardiseerde aanbevelingen. Om dit mogelijk te maken zijn wetenschappelijk betrouwbare referentiedata gebruikt met betrekking tot de validatie van laboratoriumresultaten, antimicrobiële middelen en de volledige biologische taxonomie van micro-organismen. Brondata moeten op de meest betrouwbare manier worden geanalyseerd, vooral wanneer het resultaat bijvoorbeeld gebruikt gaat worden om de behandelingsopties voor een patiënt te evalueren. Dit vereist een reproduceerbare en gespecialiseerde verwerking van data. Het AMR-pakket biedt een gestandaardiseerde en geautomatiseerde manier om gemeenschappelijke LIS-data op te schonen, te transformeren en te verbeteren, onafhankelijk van de onderliggende databron en de nauwkeurigheid van de data. Hiervoor zijn algemeen toepasbare algoritmen ontwikkeld, teneinde AMR-testresultaten te kunnen opschonen en namen van micro-organismen en antimicrobiële middelen te kunnen valideren. De formule voor de validatie van taxonomische namen houdt rekening met het vóórkomen van ziekteverwekkende micro-organismen en is contextbewust wat betreft andere taxonomische eigenschappen zoals het koninkrijk, het fylum, de orde en de familie. Ter illustratie: een waarde “E. coli” wordt vertaald naar de bacterie Escherichia coli, terwijl de gebruiker ook wordt geïnformeerd dat de parasiet Entamoeba coli in aanmerking komt, maar een lagere waarschijnlijkheid heeft. Met behulp van behendige functies kunnen gebruikers snel consistente microbiële eigenschappen opvragen, zoals het taxonomische koninkrijk, de familie, het geslacht, de soort, verouderde taxonomische namen en zelfs de Gram-kleur. Naast informatie over micro-organismen bevat het pakket ook referentiedata over antibiotica, waaronder veelvoorkomende LIS-codes, officiële namen, ATC-codes (Anatomical Therapeutic Chemical), gedefinieerde dagelijkse doses (defined daily doses, DDD) en meer dan 5.000 handelsnamen van 456 antimicrobiële middelen. Met behulp van deze referentiedata kunnen gebruikers ruwe data vertalen en eigenschappen ophalen over elk micro-organisme of antibioticum. Bovendien is het AMR-pakket in staat om multiresistente organismen (multidrug-resistant organisms, MDRO’s) te identificeren op basis van nationale en internationale richtlijnen, minimum inhibitory concentrations (MIC’s) te interpreteren en kan het de eerste isolaten bepalen die gebruikt zouden moeten worden voor het berekenen van AMR voor zowel monotherapie als combinatietherapieën. Het AMR-pakket is bedoeld als een uitgebreid instrument voor data-technisch personeel dat werkzaam is op het gebied van AMR, hoewel het gebruik ervan niet beperkt is tot deze groep.

Om dit te illustreren, toont **hoofdstuk 5** aan dat het AMR-pakket gebruikt kan worden als ruggengraat in een interactieve open-source software app voor infectiemanagement en antimicrobial stewardship, genaamd RadaR (rapid analysis of diagnostic and antimicrobial patterns in R). Infectiemanagement in de vorm van Antimicrobial Stewardship Programma’s (ASP) heeft zich ontpopt als een effectieve oplossing om het mondiale gezondheidsprobleem van antibioticaresistentie in ziekenhuizen aan te pakken. Dit sluit aan bij **hoofdstuk 2**; stewardship-interventies en -activiteiten richten zich zowel op individuele patiënten (gepersonaliseerde geneeskunde en consultatie) als op patiëntengroepen of klinische syndromen, waarbij bij elke interventie moet leiden tot verbetering van de kwaliteit van de zorg en de veiligheid van de patiënt. Het is echter moeilijk om in de dagelijkse praktijk patiëntengroepen te analyseren (bijv. gestratificeerd naar afdeling, specifieke antimicrobiële middelen, of gebruikte diagnostische procedures). Het is zelfs nog moeilijker om snel grote patiëntpopulaties te analyseren (bijv. verspreid over meerdere specialismen), ook al is deze informatie beschikbaar in de data. Daarom is de ontwikkeling van RadaR bedoeld om ASP-teams te voorzien van een gebruiksvriendelijk en tijdbesparend hulpmiddel voor data-analyse, zonder dat dit diepgaande technische expertise vereist. RadaR biedt onder andere Kaplan-Meier-curves over de ligduur in ziekenhuizen, tijdstrends voor het aantal opnames, antibioticaconsumptie, en een geautomatiseerde AMR-data-analyse waarvoor het AMR-pakket voor R gebruikt is. RadaR werd geëvalueerd door 12 ESGAP-leden (European Society of Clinical Microbiology and Infectious Diseases Study Group for Antimicrobial Stewardship) uit 9 verschillende landen. Het heeft de potentie om een zeer nuttig middel te zijn voor infectiemanagement en ASP-teams in de dagelijkse praktijk. Bovendien toont dit hoofdstuk aan, dat het AMR-pakket gebruikt kan worden als onderdeel van een andere softwareoplossing om geïntegreerd infectiemanagement mogelijk te maken.

Hieruit volgend, illustreert **hoofdstuk 6** de effectiviteit van het AMR-pakket onder gebruikers, door het evalueren van de bruikbaarheid en de impact op het werk van artsen in een typisch klinisch scenario. Hoewel het AMR-pakket in research al in meerdere studies uit verschillende landen gebruikt is, was er nog geen analyse naar de impact op workflows voor AMR-analyse en -rapportage in een klinische omgeving. De analyse en rapportage van AMR-data vereisen helaas specifiek opgeleid personeel. Bovendien kunnen AMR-data-analyses tijdrovend zijn. Om de impact hiervan in een klinische setting te bepalen, werden algemene vragen over bloedkweekdata opgesteld die door klinisch routinepersoneel moesten worden beantwoord, waaronder artsen-microbioloog, kinderartsen en intensivisten. In totaal namen tien clinici deel aan het onderzoek. Bovendien werd de deelnemers gevraagd een online vragenlijst in te vullen over hun achtergrond, demografische gegevens (zoals leeftijd en geslacht), software-ervaring en eerdere ervaring met AMR-data-analyse en -rapportage. Alle deelnemers moesten de onderzoeksvragen tweemaal beantwoorden: de eerste keer met de software van hun keuze (ronde 1) en de tweede keer met behulp van een nieuw ontwikkelde webapplicatie gebouwd rond het AMR-pakket voor R (ronde 2). Voor de ontwikkeling van deze webapplicatie werd gebruik gemaakt van een zeer efficiënte agile workflow. De antwoorden op de onderzoeksvragen dienden als basis om de effectiviteit (antwoorden op elke taak voor elke gebruiker) en efficiëntie (tijd besteed aan het oplossen van elke taak) tussen de twee rondes te vergelijken. Niet alle deelnemers waren in staat de taken binnen het gestelde tijdsbestek af te ronden. De gemiddelde taakvoltooiing tussen de eerste en tweede ronde steeg van 56% naar 96% en het percentage correcte antwoorden steeg van 38% naar 98%. De gemiddelde bestede tijd per ronde werd met meer dan een uur verminderd. Dit hoofdstuk demonstreert de verhoogde effectiviteit, efficiëntie en nauwkeurigheid van het gebruik van het AMR-pakket voor R voor AMR-data-analyse in vergelijking met traditionele software zoals Microsoft Excel en SPSS.

**Sectie III**

Veel klinische studies op het gebied van infectieziekten en microbiologie berusten op een of andere vorm van (microbiële) epidemiologie. Terwijl in de vorige sectie het AMR-pakket is gepresenteerd en het gebruik ervan in verschillende scenario’s is gedemonstreerd, begint deze sectie met een epidemiologisch researchproject in de Noord-Nederlandse regio, en breidt de sectie zich vervolgens uit tot de Nederlands-Duitse grensregio om het vóórkomen van ziekteverwekkers en diens AMR-patronen op een (eu)regionaal niveau beter te begrijpen. Door in te zoomen op de regio’s aan weerszijden van een landsgrens kunnen op microniveau vergelijkingen worden gemaakt tussen twee verschillende naties. En verschillende naties betekenen uiteindelijk verschillende gezondheidszorgsystemen. Wat blijft er over van ‘One Health’? Wat zijn de gevolgen van de verschillen tussen landen wat betreft AMR-testmethoden, MDRO-interpretaties en screeningsbeleid? Deze sectie geeft antwoorden op deze vragen.

**Hoofdstuk 7** zoomt in op coagulase-negatieve stafylokokken (CNS), waarvan bekend is dat ze bloedbaaninfecties (BBI) en een hoog sterftecijfer veroorzaken, hoewel ze jarenlang vaak als ‘slechts’ besmettelijk werden beschouwd. Bovendien worden CNS-en steeds vaker in verband gebracht met nosocomiale infecties. Momenteel bestaat de CNS-groep uit 45 verschillende species (soorten), hoewel het bepalen van het speciesniveau pas onlangs mogelijk gemaakt is voor routinediagnostische laboratoria. Sinds 2012 is namelijk MALDI-TOF-massaspectrometrie de standaard geworden voor de identificatie van bacteriële species zoals CNS. Hiervoor gebeurde de identificatie van CNS-en hoofdzakelijk met biochemische en fysiologische tests, die doorgaans variërende resultaten opleverden, in het bijzonder bij minder prevalente species. AMR, en met name multiresistentie, is ook een toenemend probleem bij CNS-en. Niettemin worden CNS-en in behandelrichtlijnen en nationale surveillanceprogramma’s (zoals het Nederlandse NethMap) nog steeds als één groep beschouwd, zonder differentiatie tussen de species. Om deze reden is er weinig bekend over trends in het vóórkomen van, en AMR in, CNS-en op lokaal en regionaal niveau. Daarom toont deze retrospectieve studie een gedetailleerde AMR-analyse van bijna 20 duizend CNS-isolaten die gevonden waren in alle beschikbare 70 duizend bloedkweekisolaten tussen 2013 en 2019 in Noord-Nederland. Met deze analyse hebben we beoogd om de verschillen in het vóórkomen van CNS-species en hun AMR-patronen te evalueren en om hun klinisch microbiologische relevantie te beoordelen. In totaal werden 27 verschillende species van de CNS-groep gevonden. Er werden grote verschillen waargenomen in het vóórkomen van de verschillende species: de top vijf omvatte 97% van alle geïncludeerde isolaten (S. epidermidis, S. hominis, S. capitis, S. haemolyticus en S. warneri). Het aandeel van CNS-en op de intensive care (IC) in vergelijking met andere afdelingen bleek ook significant te verschillen tussen tweedelijns zorg en derdelijns zorg. Omdat onbekend was welke patiënten een BBI hadden, werd ‘CNS-persistentie’ gedefinieerd als een surrogaat waarvoor ten minste drie positieve bloedkweken afgenomen moesten zijn op drie verschillende dagen binnen 60 dagen, met dezelfde CNS, bij dezelfde patiënt. De relatief meest voorkomende veroorzaker van CNS-persistentie was S. haemolyticus, gevolgd door S. epidermidis en S. lugdunensis. AMR-analyse heeft aanzienlijke verschillen tussen CNS-species aangetoond. Zo vertoonden S. epidermidis en S. haemolyticus 50% tot 80% resistentie tegen de meeste antibiotica, terwijl de resistentie tegen deze middelen bij de meeste andere CNS-en lager dan 10% bleef. Toch worden deze verschillen op nationaal niveau, zoals in NethMap, verwaarloosd, wat ertoe zou kunnen leiden dat bij de ontwikkeling van behandelrichtlijnen de nadruk wordt gelegd op veilige en vertrouwde middelen voor de behandeling van CNS, zoals vancomycine of linezolid. Niettemin kunnen middelen zoals tetracycline, cotrimoxazol en erythromycine als alternatieve opties worden beschouwd voor sommige species, waar volgens de studieresultaten de AMR nooit boven de 10% is uitgekomen. Concluderend kan worden gesteld dat een meerjarige regio-totale benadering gebruikt is om de trends in zowel het vóórkomen als de AMR van CNS-species uitgebreid te beoordelen, wat kan worden gebruikt om het behandelingsbeleid te evalueren en meer te begrijpen over deze belangrijke maar nog steeds vaak niet serieus genomen pathogenen. Bovendien diende deze studie als een praktisch voorbeeld van hoe het AMR-pakket voor R kan worden gebruikt om nieuwe AMR-inzichten te verkrijgen met behulp van epidemiologisch onderbouwde methoden.

Als vervolg op de nieuwe inzichten door het bestuderen van AMR-testresultaten in Noord-Nederland, geeft **hoofdstuk 8** een vergelijking van nationale interpretaties van MDRO’s in de Nederlands-Duitse grensregio, vooral wat betreft de praktische gevolgen voor grenspersoneel in de gezondheidszorg. Het vergelijken van AMR in het algemeen, niet alleen MDRO’s, in deze grensoverschrijdende regio is bijzonder interessant omdat beide landen worden gekenmerkt door hoog ontwikkelde, maar desondanks structureel verschillende gezondheidszorgsystemen. AMR-interpretaties in patiëntendossiers worden overgedragen tussen zorginstellingen in deze twee verschillende landen, terwijl de onderliggende definities verschillen. Hierdoor moeten clinici en deskundigen infectiepreventie de AMR-resultaten van beide kanten van de grens begrijpen en in staat zijn om beide nationale MDRO-richtlijnen toe te kunnen passen. Door antibiogrammen van Gram-negatieve bacteriën uit beide kanten van de grens met elkaar te vergelijken, werd getracht de mate van impact van deze uitdagingen te bepalen. Hiertoe werden tussen 2015 en 2016 35.619 antibiogrammen van alle soorten Enterobacteriaceae, en P. aeruginosa, het A. baumannii-complex en Stenotrophomonas maltophilia uit zes Nederlandse en vier Duitse ziekenhuizen geanalyseerd. Voor al deze soorten bestaan in deze regio MDRO-aanbevelingen en speciale infectiepreventiemaatregelen. Uit de Nederlandse ziekenhuizen werden 12.616 antibiogrammen geselecteerd met behulp van het AMR-pakket voor R waarmee ook de Nederlandse MDRO-richtlijn toegepast kon worden. Van belang is dat andere nationale en internationale richtlijnen, zoals de Duitse MDRO-richtlijn, ook zijn opgenomen in het AMR-pakket voor R. Uit Duitse ziekenhuizen werden 23.003 antibiogrammen geselecteerd. Volgens de Nederlandse richtlijn was 25% van alle isolaten een MDRO. Volgens de Duitse richtlijn was 13% van alle isolaten een MDRO. Echter, van alle isolaten werd 74% niet geclassificeerd als een MDRO volgens een van beide richtlijnen. Wanneer patiënten tussen ziekenhuizen worden overgebracht, moet ook informatie over MDRO-kolonisatie of -infectie worden overgedragen om de continue uitvoering van infectiepreventiemaatregelen te waarborgen. Voor grensoverschrijdende gezondheidszorg houdt dit in dat clinici of deskundigen infectiepreventie in staat moeten zijn MDRO’s te bepalen op basis van antibiogrammen volgens de richtlijnen van een van beide landen. Voor grensoverschrijdende gezondheidszorg zou de eenvoudigste oplossing zijn de richtlijnen van beide landen te harmoniseren. Dit zou ook een oplossing bieden voor de begrijpelijke verwarring die patiënten zouden kunnen ondervinden wanneer infectiepreventiemaatregelen in het ene land worden opgelegd, maar na overplaatsing naar een ander land weer worden opgeheven. Zolang de harmonisatie niet is gerealiseerd, moeten de volledige AMR-gegevens samen met de patiënt worden overgedragen om classificatie voor lokale deskundigen infectiepreventie mogelijk te maken.

Andere AMR-gerelateerde grensoverschrijdende uitdagingen en verschillen worden geïllustreerd in **hoofdstuk 9**, dat een uitgebreide microbiële epidemiologische analyse omvat van het vóórkomen van MRSA, en het beleid en de gevolgen voor de gezondheidszorg in het Nederlands-Duitse grensgebied. MRSA is nog steeds een van de belangrijkste oorzaken van gezondheidszorg-geassocieerde infecties als gevolg van resistente ziekteverwekkers. In deze studie werden MRSA-surveillancegegevens van vijf jaar (2012-2016) van Nederlandse en Duitse grensoverschrijdende regioziekenhuizen geanalyseerd om regio-specifieke trends in de tijd van MRSA te beschrijven en om verschillen tussen ziekenhuizengroepen vast te stellen. De studie omvatte 42 ziekenhuizen in de Nederlands-Duitse grensregio met ongeveer 620.000 opgenomen patiënten (68,0% in het Duitse deel van de onderzoeksregio) met bijna vier miljoen patiëntdagen per jaar. Alle ziekenhuizen hadden MRSA-gerelateerde infectiepreventiemaatregelen geïmplementeerd volgens hun nationale richtlijnen en aanbevelingen, en de verschillen in richtlijnen tussen de twee landen werden vergeleken. Aan beide zijden van de grens nam het MRSA-screeningspercentage tussen 2012 en 2016 aanzienlijk toe, hoewel de MRSA-incidentie in de loop van de tijd aan beide zijden van de grens stabiel bleef. In totaal was het screeningspercentage in de Duitse grensregio 14 keer hoger dan in de Nederlandse grensregio. Het percentage MRSA’s in bloedkweekisolaten met S. aureus daalde van 13% in 2012 tot 5% in 2016 in de Duitse grensregio, terwijl het stabiel bleef in de Nederlandse grensregio (0% tot 2%). Niettemin was het ruwe aantal MRSA’s onder S. aureus-isolaten 34 keer hoger in de Duitse grensregio. De ligduur in het ziekenhuis bij MRSA-patiënten was in beide regio’s vergelijkbaar, terwijl de algemene ligduur aanzienlijk verschilde. Verder bedroeg het aantal MRSA-uitstrijken voor of bij opname in het ziekenhuis per 100 inwoners 12,2 in de Duitse grensregio en 0,36 in de Nederlandse grensregio; 34 keer zo hoog in de Duitse grensregio. Het aantal intramurale MRSA-gevallen per 1.000 inwoners bedroeg 2,52 in de Duitse grensregio en 0,14 in de Nederlandse grensregio. Dit onderzoek liet dus significante verschillen zien tussen Nederlandse en Duitse ziekenhuizen. De MRSA-incidentie in Duitse ziekenhuizen was meer dan zeven keer hoger dan in Nederlandse ziekenhuizen. Volgens het European Centre of Disease Prevention and Control (ECDC) worden verschillen in het vóórkomen van resistente ziekteverwekkers tussen Europese landen hoogstwaarschijnlijk veroorzaakt door verschillen in zorggebruik, antimicrobieel gebruik en infectiepreventiemaatregelen. Wat het zorggebruik in onze context betreft, stelden wij vast dat inwoners in het Duitse deel van het studiegebied bijna drie keer zo vaak in het ziekenhuis werden opgenomen en een aanzienlijk langere ligduur hadden dan patiënten in het Nederlandse deel. Dit kan te wijten zijn aan sociaaleconomische factoren of een andere inrichting van ambulante gezondheidszorg. Deze uitgebreide studie over MRSA in ziekenhuizen rond een Europese grens heeft aangetoond dat routinematige MRSA-surveillance nuttig kan zijn om trends van MRSA te volgen, om zodoende (inter)nationale vergelijkingen mogelijk te maken.

De discussie van deze studie werd afgesloten met (vertaald) “grensoverschrijdende surveillance moet worden uitgebreid naar andere multiresistente micro-organismen”, wat precies is waar **hoofdstuk 10** op voortborduurt. Aangezien niet alleen MRSA’s maar MDRO’s in het algemeen een risico vormen voor de gezondheidszorg, zowel in de gemeenschap als in ziekenhuizen, had deze studie tot doel de prevalentie van meerdere MDRO’s in deze grensoverschrijdende regio vast te stellen om verschillen te begrijpen en infectiepreventie te verbeteren op basis van real-time routinegegevens. Hiertoe namen 23 ziekenhuizen in de Nederlands-Duitse grensregio tussen 2017 en 2018 deel aan deze prospectieve studie door alle patiënten bij opname op de IC te screenen. Alle ziekenhuizen (8 in Nederland, 15 in Duitsland) screenden patiënten gedurende acht opeenvolgende weken op dragerschap van MRSA, vancomycineresistente Enterococcus faecium/E. faecalis (VRE), derde-generatie cefalosporine-resistente Enterobacteriaceae (3GCRE) en carbapenem-resistente Enterobacteriaceae (CRE). In totaal werden 3.365 patiënten gescreend: 36% op Nederlandse IC’s en 64% op Duitse IC’s. De mediane leeftijd van alle gescreende patiënten was 68 jaar (IQR: 57-77), waarbij patiënten in de Duitse grensregio significant ouder waren dan patiënten in de Nederlandse grensregio. De algemene screening compliance (gescreend op ten minste één MDRO-groep) was 60%. Alle AMR-data-analyses werden uitgevoerd en geautomatiseerd met behulp van het AMR-pakket voor R. De prevalentie van MRSA was 1,7% op Duitse IC’s en 0,6% op Nederlandse IC’s. De prevalentie van VRE was 2,7% op Duitse IC’s en 0,1% op Nederlandse IC’s. Opmerkelijk is dat deze prevalentie varieerde van 0% tot 4,1% in het Duitse grensgebied. Alle 56 gevallen van VRE werden veroorzaakt door E. faecium. De prevalentie van 3GCRE was 6,6% op Duitse IC’s en 3,6% op Nederlandse IC’s, terwijl de prevalentie voor CRE aan beide zijden van de grens nagenoeg nihil was. De prevalentie voor Gram-negatieve MDRO’s verschilde tussen ziekenhuizen in beide landen, variërend van 0% tot 5,0% in de Nederlandse grensregio en van 1,2% tot 10,9% in de Duitse grensregio. Voor de geïncludeerde Nederlandse IC’s was de prevalentie van alle MDRO-groepen niet significant verschillend tussen tweedelijns en derdelijns ziekenhuizen. Voor de Duitse IC’s was de prevalentie van Gram-negatieve MDRO’s echter significant hoger in de tweedelijns ziekenhuizen. In de Nederlandse grensregio leidde 4,8 per 100 ziekenhuisopnamen tot een IC-opname. In de Duitse grensregio was dit daarentegen 7,7 per 100 ziekenhuisopnames. Dit verschil kan worden verklaard door de hogere IC-capaciteit in Duitse ziekenhuizen (4,8% van alle ziekenhuisbedden) in vergelijking met Nederlandse ziekenhuizen (2,4% van alle ziekenhuisbedden). De algemene prevalentie van de verschillende MDRO’s was hoger op de Duitse IC’s, hoewel sommige verschillen marginaal waren. Met name de prevalentie van MRSA was drie keer hoger in de Duitse grensregio dan in de Nederlandse grensregio, wat consistent is met de onderzoeksresultaten in **hoofdstuk 9**. Toch waren de onderzoeksresultaten niet consistent met (inter)nationale gemiddelden. Zo was de 3GCRE-prevalentie bijna twee keer zo hoog in de Duitse grensregio als in de Nederlandse grensregio, maar beide waren nog steeds lager dan de nationale gemiddelden; de ECDC meldde 6% hogere 3GCRE-percentages onder E. coli en K. pneumoniae uit bloedkweken voor Duitsland en Nederland. Hieruit blijkt dat er belangrijke verschillen zijn tussen het bestuderen van dragerschap in bepaalde populaties en het bestuderen van het aandeel van (waarschijnlijk) invasieve isolaten. Deze studie benadrukt daarmee het belang van een regionale en grensoverschrijdende aanpak in een Europese grensregio, om het verschil in AMR-prevalentie tussen de regio’s te illustreren en om potentiële verschillen met nationale rapporten te belichten. Om dit verder te kunnen uitwerken is een dieper detailniveau nodig, bijvoorbeeld door informatie te verzamelen over (infectiepreventie)personeel, MDRO-uitbraken, infecties, antibioticagebruik en risicofactoren van patiënten. Concluderend lijken geografische en politieke grenzen door MDRO’s niet te worden “gerespecteerd”, hoewel de gezondheidszorgsystemen, de geografische aard en de richtlijnen van land tot land sterk verschillen. De percentages MDRO’s van bepaalde ziekteverwekkers, zoals gerapporteerd op nationaal en internationaal niveau, weerspiegelen niet de prevalentie van MDRO’s in de patiënt of in de algemene bevolking. Dit moet ernstig in overweging worden genomen bij de interpretatie van rapporten op nationaal of zelfs continentaal niveau.

**Conclusie**

Vanuit verschillende invalshoeken worden het AMR-pakket en zijn voordelen in perspectief geplaatst: vanuit een technisch perspectief, vanuit het perspectief van infectiemanagement en vanuit een klinisch perspectief. Deze combinatie biedt een gemeenschappelijke basis voor het begrijpen van de oplossingen die het AMR-pakket kan bieden en hoe het een nieuw startpunt kan vormen voor toekomstige toepassingen van microbiële epidemiologie, zowel in klinische settings als in wetenschappelijk onderzoek. Dit proefschrift gaat vervolgens in op deze verschillende invalshoeken door het gebruik van dit nieuwe instrument te illustreren in epidemiologische studies in de Nederlands-Duitse grensregio om het vóórkomen en de AMR-trends van micro-organismen op (eu)regionaal niveau beter te begrijpen. Concluderend toont dit proefschrift de toegevoegde waarde aan van een consistent data-analytisch instrument om AMR-data voor te bereiden en te analyseren in een regio-overstijgende benadering, om nieuwe inzichten te verkrijgen in AMR-trends.
