# Zusammenfassung auf Deutsch {-}

*Ein wichtiger Teil dieser Dissertation (insbesondere Abschnitt III) wurde durch die sehr gute und vor allem herzliche Zusammenarbeit mit deutschen Kollegen:innen ermöglicht. Diese Zusammenfassung ist eine freundliche Geste an meine deutschen Kollegen:innen.*

**Abschnitt I**

Wo liegen die Anfänge der mikrobiellen Epidemiologie? Wie ist sie entstanden? Und wie trägt sie zu einem umfassenden Ansatz in der Behandlung von Patient:innen mit Infektionen bei? Diese Fragen werden in diesem ersten Abschnitt beantwortet. Anschließend werden die wichtigsten derzeitigen Hindernisse bei der Anwendung der mikrobiellen Epidemiologie in der Praxis beschrieben und wie diese überwunden werden könnten.

Die allgemeine Einleitung dieser Dissertation skizziert in **Kapitel 1**, dass die mikrobielle Epidemiologie ein Teil der Infektionsepidemiologie ist, die wiederum ein Teil der klinischen Mikrobiologie ist. Die mikrobielle Epidemiologie kann unter anderem als das wissenschaftliche Feld zur Gewinnung neuer Erkenntnisse über sich ausbreitende Mikroorganismen und deren jeweilige Muster der antimikrobiellen Resistenz (AMR) gesehen werden. Die Fortschritte in der Informationstechnologie haben uns nicht nur die Möglichkeiten gebracht, über regionale, nationale und internationale Grenzen hinweg zu schauen, um ein Verständnis für die Ausbreitung von Mikroorganismen und AMR zu bekommen, sondern sogar Pandemien in Echtzeit zu beobachten, zu analysieren und zu verstehen. Methoden, die wir heute entwickeln und anwenden, können morgen auf der anderen Seite der Welt eingesetzt werden. Dies ist ein wichtiger Vorteil in der modernen mikrobiellen Epidemiologie, deren Fokus zunehmend datengetriebener wird.

Um diesen Fokus voranzutreiben, sind Daten die wichtigste Voraussetzung. Die Daten, die als Input für mikrobielle epidemiologische Analysen verwendet werden, werden häufig aus Laborinformationssystemen (LIS) gewonnen. Diese Daten bestehen aus Routine-diagnoseergebnissen von Labortests. In **Kapitel 2** wird die Ansicht erörtert, dass die Diagnostik zwar zu Rohdaten führt, aber nicht zu einer direkten Antwort auf die klinische Frage, die ein Arzt, der einen Patient:innen behandelt, haben könnte. Um Ärzten Antworten zu geben, ist der Ansatz eines multidisziplinären, ineinandergreifenden ‚Stewardship'-Konzepts mit Schwerpunkt auf der Diagnostik erforderlich. Dies erfordert ein enges Zusammenspiel von Fachärzten im Allgemeinen und Mikrobiologen im Besonderen für eine optimale Versorgungsqualität und Patientensicherheit um erfolgreiches Infektions-management ausführen zu können: Diagnostic Stewardship Programme (DSP). Das Konzept des Stewardships wurde im Allgemeinen weithin verwendet, um die Kommunikation und die klinische Entscheidungsfindung zu erleichtern, wobei es sich als schwierig erwies, eine klare Definition des Begriffs "Stewardship" festzulegen. Darüber hinaus macht die Diagnostik in klinisch-mikrobiologischen Laboratorien derzeit rasante Fortschritte im Hinblick auf verbesserte Arbeitsabläufe und neue Technologien, wie z. B. die matrixunterstützte Laser-Desorptions/Ionisations-Time-of-Flight (MALDI-TOF) Massenspektrometrie. Die Diagnostik im Infektionsmanagement ist jedoch breiter angelegt und umfasst viele klinische Bereiche, in denen Kommunikation und Interaktion von grundlegender Bedeutung sind, um das Wissen und die Expertise optimal zu nutzen, was dazu führt, dass alle Fachrichtungen einen Beitrag zur Patientenversorgung leisten. Der richtige Test zur richtigen Zeit für den richtigen Patient:innen, um die richtigen Fragen zu beantworten und die richtige Behandlung einzuleiten - darum geht es beim DSP in der klinischen Mikrobiologie. Die mikrobielle Epidemiologie kann für einen kleinen Aspekt dieser diagnostischen Gesamtheit genutzt werden, indem die Testergebnisse wiederverwertet werden und anschließend Anreicherungen in den Prozess zur Generierung von Antworten einbringen, den DSP verkörpert.

Hier setzt **Kapitel 3** an, indem es wichtige aktuelle Einschränkungen bei der Anwendung der mikrobiellen Epidemiologie, insbesondere der AMR-Datenanalyse, hervorhebt. Insbesondere muss die AMR-Datenanalyse auf eine klinisch und epidemiologisch sinnvolle Weise durchgeführt werden, was jedoch eine Herausforderung darstellt, da man dafür Fachwissen in (klinischer) Epidemiologie und (klinischer) Mikrobiologie sowie Werkzeuge zur Handhabung der AMR-Datenanalyse benötigt. Dies wird zusätzlich durch die häufig fehlende Zugänglichkeit der in LIS-es gespeicherten Daten erschwert, da die meisten LIS-es nicht mit einem Fokus auf Epidemiologie konzipiert sind. So führt beispielsweise jedes LIS seine eigenen taxonomischen Daten und die Labore sind für deren regelmäßige Aktualisierung verantwortlich. Da die AMR-Richtlinien stark auf der mikrobiellen Taxonomie basieren (einige Regeln gelten nur für eine bestimmte Gattung, andere Regeln gelten für eine bestimmte Familie), müssen diese Informationen korrekt und aktuell sein. Leider wurde bei der Untersuchung von sieben klinischen Mikrobiologie-Laboren in den Niederlanden festgestellt, dass alle ihre LIS-es stark veraltete taxonomische Namen enthielten. Dies kann sowohl die routinemäßige Ergebnismeldung als auch (zukünftige) epidemiologische Analysen beeinträchtigen. Aus diesen Gründen wurde in diesem Kapitel das AMR-Paket für R, eine Programmiersprache für statistische Berechnungen, als neues epidemiologisches Instrument zur AMR-Datenanalyse vorgestellt. Das AMR-Paket ist kostenlos, unabhängig, Open Source und öffentlich zugänglich. Es wurde mit einem Team aus zwölf verschiedenen Organisationen des öffentlichen Gesundheitswesens in sieben verschiedenen Nationen entwickelt und bietet Werkzeuge zur Vereinfachung der AMR-Datenbereinigung, -transformation und -analyse sowie Methoden zur einfachen Einbindung (inter)nationaler Richtlinien und wissenschaftlich zuverlässiger Referenzdaten. Mit Stand Mai 2021 wurde das AMR-Paket seit seiner ersten Veröffentlichung im Jahr 2018 mindestens 50.000-mal aus 162 verschiedenen Nationen heruntergeladen. Die Ergebnisse einer Umfrage unter den Nutzern, die in diesem Kapitel vorgestellt werden, zeigten, dass seine Verwendung zu einer besseren Reproduzierbarkeit von Analyseergebnissen, verlässlicheren Ergebnissen von AMR-Datenanalysen und neuen oder verbesserten Erkenntnissen zu AMR für die Institutionen und Regionen der Nutzer führte. Die Anwender gaben auch an, dass das AMR-Paket zur Unterstützung der klinischen Entscheidungsfindung eingesetzt wurde. Das Paket löst die Unannehmlichkeit, von (inter)nationalen Richtlinien und zuverlässigen (Referenz-)Daten abhängig zu sein, und bietet gleichzeitig eine umfassende Toolbox für die Analyse selbst. Das AMR-Paket für R kann daher jeden Spezialisten auf dem Gebiet, der mit AMR-Daten arbeitet, unterstützen.

**Abschnitt II**

Nach den im vorherigen Abschnitt beschriebenen Herausforderungen wird in diesem Abschnitt das AMR-Paket für R als neues Instrument zur Bewältigung dieser Herausforderungen vorgestellt. Das AMR-Paket und seine Vorteile werden aus verschiedenen Blickwinkeln betrachtet: aus technischer Sicht, aus Sicht des Infektionsmanagements und aus klinischer Sicht. Diese Kombination bietet eine gemeinsame Grundlage für das Verständnis der Erklärungen, die das AMR-Paket im Feld liefern kann und wie es einen neuen Ausgangspunkt für zukünftige Anwendungen der mikrobiellen Epidemiologie setzen kann.

Die technischen Funktionalitäten des AMR-Pakets für R wurden in **Kapitel 4** beschrieben. Dort wird beschrieben, wie das AMR-Paket entwickelt wurde, um saubere und reproduzierbare AMR-Datenanalysen unter Verwendung internationaler Richtlinien zu standardisieren. Um dies zu ermöglichen, werden wissenschaftlich verlässliche Laborreferenzdaten, antimikrobieller Wirkstoffe und der vollständigen biologischen Taxonomie der Mikroorganismen einbezogen. Die Quelldaten sollten so zuverlässig wie möglich analysiert werden, vor allem, wenn die Ergebnisse z. B. zur Bewertung von Behandlungsoptionen für Patient:innen herangezogen werden sollen. Dies erfordert eine reproduzierbare und feldspezifische, spezialisierte Datenbereinigung und -transformation. Das AMR-Paket bietet eine standardisierte und automatisierte Möglichkeit, allgemeine LIS-Daten zu bereinigen, zu transformieren und zu verbessern, unabhängig von der zugrunde liegenden Datenquelle und der Datengenauigkeit. Aus diesem Grund wurden allgemeine Algorithmen zur Bereinigung von AMR-Daten und zur Validierung der Namen von Mikroorganismen und antimikrobiellen Wirkstoffen entwickelt. Die Gleichung zur taxonomischen Namensvalidierung berücksichtigt die humanpathogene Prävalenz von Mikroorganismen und ist kontextbewusst über andere taxonomische Eigenschaften wie das Königreich, Phylum, Ordnung und Familie. So wird z. B. ein Datenwert "E. coli" in das Bakterium Escherichia coli übersetzt, während der Benutzer darüber informiert wird, dass der Parasit Entamoeba coli ebenfalls in Frage kommt, aber eine geringere Wahrscheinlichkeit hat. Mit Hilfe einfacher Funktionen können Benutzer schnell konsistente mikrobielle Eigenschaften abrufen, wie z. B. das taxonomische Königreich, die Familie, Gattung, Art, früher akzeptierte Namen und sogar die Gram-Färbung. Neben den Informationen über Mikroorganismen enthält das Paket auch Referenzdaten über Antibiotika, die gängige Laborinformationssystem-Codes, offizielle Wirkstoffnamen, ATC-Codes (Anatomical Therapeutic Chemical), definierte Tagesdosen (DDD) und mehr als 5.000 Handelsnamen von 456 antimikrobiellen Wirkstoffen umfassen. Mit Hilfe dieser Referenzdaten können Anwender Rohdaten übersetzen und Eigenschaften über jeden Mikroorganismus oder antimikrobiellen Wirkstoff abrufen. Darüber hinaus ist das AMR-Paket in der Lage, multiresistente Organismen (multi-drug resistant organisms, MDROs) auf der Grundlage nationaler und internationaler Richtlinien zu bestimmen, minimale Hemmkonzentrationen (MHKs) zu interpretieren und erste Isolate zu bestimmen, die für die Berechnung der AMR sowohl von Monotherapien als auch von Kombinationstherapien verwendet werden können. Das AMR-Paket selbst war als umfassendes Instrument für datentechnisches Personal gedacht, das auf dem Gebiet der AMR arbeitet, obwohl seine Verwendung nicht auf diese Gruppe beschränkt ist.

Um dies zu veranschaulichen, zeigt **Kapitel 5**, dass das AMR-Paket als Rückgrat in einer interaktiven Open-Source-Software-App für Infektionsmanagement und antimikrobiellem Stewardship, genannt RadaR (Rapid Analysis of Diagnostic and Antimicrobial patterns in R; schnelle Analyse von diagnostischen und antimikrobiellen Mustern in R), verwendet wurde. Infektionsmanagement in Form von Antimicrobial Stewardship (AMS)-Programmen hat sich als effektive Lösung herausgestellt, um dieses globale Gesundheitsproblem in Krankenhäusern anzugehen. Anknüpfend an **Kapitel 2** konzentrieren sich Stewardship-Interventionen und -Aktivitäten sowohl auf einzelne Patient:innen (personalisierte Medizin und Beratung) als auch auf Patientengruppen oder klinische Syndrome (Richtlinien, Protokolle, informations-technische Infrastruktur und klinische Entscheidungsunterstützungssysteme), wobei die Verbesserung der Versorgungsqualität und der Patientensicherheit bei jeder Intervention im Vordergrund steht. Der einfache Zugang zur Analyse von Patientengruppen (z. B. stratifiziert nach Abteilungen oder Stationen, spezifischen antimikrobiellen Mitteln oder verwendeten diagnostischen Verfahren) ist jedoch in der täglichen Praxis schwer umzusetzen. Noch schwieriger ist es, größere Patientenpopulationen (z. B. über mehrere Fachrichtungen verteilt) schnell zu analysieren, auch wenn diese Informationen in den Daten vorhanden sein könnten. Daher war die Entwicklung von RadaR darauf ausgerichtet, AMS-Teams eine benutzerfreundliche und zeitsparende Datenanalyseressource zur Verfügung zu stellen, ohne dass tiefgreifende technische Fachkenntnisse erforderlich sind. RadaR wurde für die grafische explorative (AMR) Datenanalyse entwickelt. Es bietet unter anderem Kaplan-Meier-Kurven über die Verweildauer im Krankenhaus, Zeittrends für die Anzahl der Aufnahmen, den Verbrauch von antimikrobiellen Mitteln und eine automatisierte AMR-Datenanalyse, für die das AMR-Paket für R verwendet wurde. RadaR wurde von 12 ESGAP-Mitgliedern (European Society of Clinical Microbiology and Infectious Diseases Study Group for Antimicrobial Stewardship) aus 9 verschiedenen Nationen evaluiert. Es hat das Potenzial, ein sehr nützliches Werkzeug für Infektionsmanagement und AMS-Teams in der täglichen Praxis zu sein. Zusätzlich zeigt dieses Kapitel, dass das AMR-Paket als Teil einer anderen Softwarelösung verwendet werden kann, um ein integriertes Infektionsmanagement zu ermöglichen.

Nach dieser Erkenntnis wird in **Kapitel 6** die Effektivität des AMR-Pakets bei den Anwendern demonstriert, indem die Benutzerfreundlichkeit und die Auswirkungen auf die Arbeitsabläufe der Kliniker:innen in einem typischen Krankenhausszenario bewertet werden. Obwohl die Verwendung des AMR-Pakets in der Forschung bereits in mehreren Studien aus verschiedenen Nationen nachgewiesen wurde, stand die Auswirkung auf die Arbeitsabläufe für die AMR-Datenanalyse und -berichterstattung in klinischen Umgebungen noch aus. AMR-Datenanalyse und -reporting erfordern speziell geschultes Personal. Darüber hinaus können gründliche und tiefgehende Analysen zeitaufwendig sein und es müssen ausreichend Ressourcen für eine konsistente und wiederholte Berichterstattung bereitgestellt werden. Um die Auswirkungen dieser Tatsachen in einem klinischen Umfeld zu ermitteln, wurden allgemeine Fragen zu Blutkulturdaten formuliert, die von klinischem Personal, einschließlich klinischen Mikrobiologen:innen, Pädiater:innen und Intensivmedizinern:innen, beantwortet werden mussten. Insgesamt nahmen zehn Kliniker:innen an der Studie teil. Zusätzlich wurden die Teilnehmer:innen gebeten, einen Online-Fragebogen auszufüllen, in dem ihr Hintergrund, ihre demografischen Daten, ihre Software-Erfahrung und ihre Erfahrung mit der Analyse und Berichterstattung von AMR-Daten erfasst wurden. Alle Teilnehmer:innen mussten die Studienfragen zweimal beantworten: das erste Mal mit der Software ihrer Wahl (Runde 1) und das zweite Mal mit einer neu entwickelten Webanwendung, die auf dem AMR-Paket für R aufbaut (Runde 2). Die Entwicklung dieser Webanwendung wurde in einem hocheffizienten und agilen Workflow ausgeführt. Die Antworten auf den Fragenkatalog dienten als Grundlage, um die Effektivität (Lösbarkeit jeder Aufgabe für jeden Benutzer) und Effizienz (Zeitaufwand für die Lösung jeder Aufgabe) zwischen den beiden Runden zu vergleichen. Nicht alle Teilnehmer waren in der Lage, die Aufgaben innerhalb des vorgegebenen Zeitrahmens zu lösen. Die durchschnittliche Aufgabenerfüllung zwischen der ersten und zweiten Runde stieg von 56% auf 96% und der Anteil der richtigen Antworten stieg von 38% auf 98%. Der mittlere Zeitaufwand pro Runde wurde mit mehr als einer Stunde reduziert. Dieses Kapitel zeigt die erhöhte Effektivität, Effizienz und Genauigkeit der Verwendung des AMR-Pakets für R zur AMR-Datenanalyse im Vergleich zu herkömmlichen Softwareanwendungen wie Microsoft Excel und SPSS.

**Abschnitt III**

Viele klinische Studien auf dem Gebiet der Infektionskrankheiten und der Mikrobiologie stützen sich auf eine Form der (mikrobiellen) Epidemiologie. Während das AMR-Paket im vorherigen Abschnitt vorgestellt und seine Verwendung in verschiedenen Umgebungen gezeigt wurde, beginnt dieser Abschnitt mit einem epidemiologischen Forschungsprojekt in der nordniederländischen Region und dehnt sich dann auf die niederländisch-deutsche Grenzregion aus, um das Auftreten und die AMR-Muster von Krankheitserregern auf (eu)regionaler Ebene zu verstehen. Die Fokussierung auf die Regionen auf beiden Seiten einer nationalen Grenze ermöglicht Vergleiche zwischen zwei verschiedenen Nationen auf der Mikroebene. Und unterschiedliche Nationen bedeuten letztlich unterschiedliche Gesundheitssysteme. Was bleibt von „One Health“ übrig? Welche Auswirkungen hat es auf den Vergleich, wenn sich die Nationen in Bezug auf AMR-Testmethoden, MDRO-Interpretationen und Screening-Richtlinien unterscheiden? Dieser Abschnitt gibt Antworten auf diese Fragen. 

**Kapitel 7** befasst sich mit Koagulase-negativen Staphylokokken (KNS), die bekanntermaßen Blutbahninfektionen (BSI) und eine hohe Sterblichkeitsrate verursachen, obwohl sie jahrelang oft als Kontamination angesehen wurden. Außerdem werden KNS zunehmend mit nosokomialen Infektionen in Verbindung gebracht. Derzeit besteht die Gruppe der KNS aus 45 verschiedenen Spezies, wobei die Bestimmung der Spezies-Ebene erst seit kurzem für diagnostische Routinelabore möglich ist. Seit 2012 ist die MALDI-TOF-Massenspektrometrie zum Standard für die Identifizierung von Bakterienarten wie KNS geworden. Davor erfolgte die Identifizierung von KNS vor allem mit biochemischen und physiologischen Tests, die insbesondere bei weniger verbreiteten Spezies generell variable Ergebnisse lieferten. AMR, und insbesondere Multiresistenz, ist auch bei KNS ein zunehmendes Problem. Dennoch erfassen Behandlungsrichtlinien und nationale Überwachungsprogramme (wie z. B. das niederländische NethMap) KNS immer noch als eine Gesamtgruppe, wobei eine Differenzierung zwischen den Arten fehlt. Folglich ist wenig über Trends im Auftreten und AMR bei KNS auf lokaler und regionaler Ebene bekannt. Daher zeigt diese retrospektive Studie eine eingehende AMR-Analyse von fast 20 Tausend KNS-Isolaten, die in allen verfügbaren 70 Tausend Blutkulturisolaten zwischen 2013 und 2019 in den nördlichen Niederlanden gefunden wurden. Diese Studie folgte einem flächendeckenden Ansatz, indem sie die gesamten nördlichen Niederlande abdeckte. Ziel dieser Analyse war es, die Unterschiede im Vorkommen von KNS-Spezies und deren AMR-Muster zu bewerten und die klinisch-mikrobiologische Relevanz zu beurteilen. Insgesamt wurden 27 verschiedene Spezies der KNS-Gruppe gefunden. Es wurden große Unterschiede im Vorkommen der verschiedenen Spezies beobachtet: Die fünf wichtigsten Spezies deckten 97% aller eingeschlossenen Isolate ab (S. epidermidis, S. hominis, S. capitis, S. haemolyticus und S. warneri). Der Anteil von KNS auf Intensivstationen (ICUs) im Vergleich zu anderen Abteilungen unterschied sich ebenfalls signifikant zwischen der Sekundärversorgung und der Tertiärversorgung. Da nicht bekannt war, bei welchen Patient:innen BSI auftraten, wurde "KNS-Persistenz" als Surrogat für mindestens drei positive Blutkulturen definiert, die an drei verschiedenen Tagen innerhalb von 60 Tagen gezogen wurden und dieselbe KNS-Spezies enthielten, und zwar bei demselben Patient:innen. Der relativ häufigste Erreger von KNS-Persistenz war S. haemolyticus, gefolgt von S. epidermidis und S. lugdunensis. Die AMR-Analyse zeigte erhebliche Unterschiede zwischen den KNS-Spezies. Zum Beispiel zeigten S. epidermidis und S. haemolyticus 50% bis 80% Resistenz gegen die meisten Antibiotika, während die Resistenz gegen diese Mittel bei den meisten anderen KNS-Spezies unter 10% lag. Dennoch werden diese Unterschiede auf nationaler Ebene wie in NethMap vernachlässigt, was dazu führen könnte, dass sich die Entwicklung von Behandlungsrichtlinien auf „AMR-sichere“ Wirkstoffe zur Behandlung von KNS konzentriert, wie z. B. Vancomycin oder Linezolid. Nichtsdestotrotz könnten Wirkstoffe wie Tetracyclin, Co-Trimoxazol und Erythromycin als brauchbare Optionen für einige Spezies angesehen werden, bei denen die AMR laut den Studienergebnissen nie mehr als 10% betrug. Zusammenfassend lässt sich sagen, dass ein mehrjähriger, flächendeckender Ansatz zur umfassenden Bewertung der Trends sowohl des Auftretens als auch der AMR von KNS-Spezies durchgeführt wurde, der zur Bewertung von Behandlungsstrategien und zum besseren Verständnis dieser wichtigen, aber immer noch zu oft vernachlässigten Krankheitserreger genutzt werden konnte. Darüber hinaus diente diese Studie als praktisches Forschungsbeispiel dafür, wie das AMR-Paket für R genutzt werden kann, um mit epidemiologisch fundierten Methoden neue Erkenntnisse über AMR zu gewinnen.

Nach neuen Erkenntnissen durch die Untersuchung von AMR-Testergebnissen in den nördlichen Niederlanden bietet **Kapitel 8** einen Vergleich von ihren nationalen Interpretationen von MDROs in der deutsch-niederländischen Grenzregion, insbesondere hinsichtlich der praktischen Auswirkungen auf das grenzüberschreitende Gesundheitspersonal. Der Vergleich von AMR im Allgemeinen, nicht nur MDROs, in dieser grenzüberschreitenden Region ist besonders interessant, da beide Nationen durch hoch entwickelte, aber strukturell unterschiedliche Gesundheitssysteme gekennzeichnet sind. AMR-Interpretationen in Patientenakten werden zwischen Gesundheitseinrichtungen in diesen beiden unterschiedlichen Nationen übertragen, während die zugrunde liegenden MDRO Definitionen unterschiedlich sind. Daraus ergibt sich die Notwendigkeit für Kliniker:innen und Hygienespezialist:innen, AMR-Ergebnisse von beiden Seiten der Grenze zu verstehen und in der Lage zu sein, beide nationalen MDRO-Interpretationsrichtlinien nachzuvollziehen. Durch den Vergleich von Antibiogrammen Gram-negativer Bakterien von beiden Seiten der Grenze wurde versucht, den Grad der Auswirkungen dieser Herausforderungen zu bestimmen. Zu diesem Zweck wurden 35 Tausend Antibiogramme aus sechs niederländischen und vier deutschen Krankenhäusern zwischen 2015 und 2016 von allen Arten von Enterobacteriaceae sowie P. aeruginosa, dem A. baumannii-Komplex und Stenotrophomonas maltophilia analysiert. Für alle diese Spezies gibt es in dieser Region MDRO-Empfehlungen und spezielle Hygienemaßnahmen. Aus den niederländischen Krankenhäusern wurden Antibiogramme mit Hilfe des AMR-Pakets für R unter Anwendung der niederländischen MDRO-Interpretationsleitlinie ausgewählt. Es sei darauf hingewiesen, dass auch andere nationale und internationale Richtlinien, wie die deutsche MDRO-Interpretationsrichtlinie, im AMR-Paket für R enthalten sind. Nach der niederländischen Leitlinie waren 25% aller Isolate ein MDRO. Nach der deutschen Leitlinie waren 13% aller Isolate ein MDRO. Von allen Isolaten wurden jedoch 74% nach keiner der beiden Richtlinien als MDRO eingestuft. Wenn Patient:innen zwischen Krankenhäusern verlegt werden, müssen auch Informationen über MDRO-Besiedlung oder -Infektion übertragen werden, um eine kontinuierliche Umsetzung von Infektionskontrollmaßnahmen zu gewährleisten. Für die grenzüberschreitende Gesundheitsversorgung bedeutet dies, dass Kliniker:innen oder Hygienespezialist:innen in der Lage sein sollten, MDROs anhand von Antibiogrammen gemäß den Richtlinien beider Nationen zu bestimmen. Für die grenzüberschreitende Gesundheitsversorgung wäre die einfachste Lösung, die Definitionen der beiden Nationen zu harmonisieren. Dies könnte auch die verständliche Verwirrung lösen, die bei Patient:innen auftreten kann, wenn in einem Land Maßnahmen zur Infektionsprävention auferlegt werden, diese aber nach der Verlegung in ein anderes Land wieder aufgehoben werden. Solange die Harmonisierung nicht erfolgt ist, sollten die vollständigen AMR-Daten von Gram-negativen Bakterien zusammen mit dem Patient:innen übertragen werden, um eine Klassifizierung durch das lokale Infektionskontrollpersonal zu ermöglichen. 

Weitere AMR-bedingte grenzüberschreitende Herausforderungen und Unterschiede werden in **Kapitel 9** veranschaulicht, das eine umfassende mikrobielle epidemiologische Analyse des MRSA-Vorkommens, der Maßnahmen und der Auswirkungen auf das Gesundheitswesen in der deutsch-niederländischen Grenzregion umfasst. MRSA ist immer noch eine der Hauptursachen für therapieassoziierte Infektionen aufgrund von AMR-Erregern. In dieser Studie wurden MRSA-Surveillance-Daten von fünf Jahren (2012-2016) aus Krankenhäusern der niederländischen und deutschen Grenzregion analysiert, um zeitliche und räumliche Trends der MRSA-Raten zu beschreiben und Unterschiede zwischen diesen Gruppen von Krankenhäusern zu finden. Das Forschungssetting umfasste 42 Krankenhäuser in der deutsch-niederländischen Grenzregion, die etwa 620.000 aufgenommene Patient:innen (68% im deutschen Teil der Studienregion) mit fast vier Millionen Patiententagen pro Jahr behandelten. Alle Krankenhäuser hatten MRSA-bezogene Maßnahmen zur Infektionsprävention entsprechend ihren nationalen Richtlinien und Empfehlungen implementiert, und die Richtlinienunterschiede zwischen den beiden Nationen wurden verglichen. Auf beiden Seiten der Grenze stieg die MRSA-Screening-Rate zwischen 2012 und 2016 signifikant an, obwohl die MRSA-Inzidenz auf beiden Seiten der Grenze im Zeitverlauf stabil blieb. Insgesamt war die Screening-Rate in der deutschen Grenzregion 14-mal höher als in der niederländischen Grenzregion. Der Teil von MRSA in S. aureus-Blutkulturisolaten sank von 13% im Jahr 2012 auf 5% im Jahr 2016 in der deutschen Grenzregion, aber blieb stabil in der niederländischen Grenzregion (0% bis 2%). Dennoch war die Anzahl von MRSA unter den S. aureus-Isolaten in der deutschen Grenzregion 34-mal höher. Die Länge des Krankenhausaufenthalts von MRSA-Patient:innen war in beiden Regionen ähnlich, während sich die allgemeine Länge signifikant unterschied. Außerdem war die Anzahl der MRSA-Screening-Abstriche vor oder bei der Aufnahme ins Krankenhaus 12,2 pro 100 Einwohner in der deutschen Grenzregion und 0,36 in der niederländischen Grenzregion, ebenfalls 34-mal höher in DE-BR. Die Anzahl der stationären MRSA-Fälle pro 1.000 Einwohner lag in der deutschen Grenzregion bei 2,52 und in der niederländischen Grenzregion bei 0,14. Somit zeigte diese Studie signifikante Unterschiede zwischen niederländischen und deutschen Krankenhäusern. Die MRSA-Inzidenz in deutschen Krankenhäusern war mehr als siebenmal höher als in niederländischen Krankenhäusern. Nach Angaben des Europäischen Zentrums für die Prävention und die Kontrolle von Krankheiten (ECDC) werden Unterschiede im Auftreten von AMR-Erregern zwischen den europäischen Nationen höchstwahrscheinlich durch Unterschiede in der Nutzung des Gesundheitswesens, der Verwendung von antimikrobiellen Mitteln und den Praktiken zur Infektionsprävention verursacht. In Bezug auf die Inanspruchnahme des Gesundheitswesens in unserem Kontext stellten wir fest, dass die Bewohner im deutschen Teil der Studienregion fast dreimal so häufig ins Krankenhaus eingeliefert wurden und eine signifikant längere Länge des Krankenhausaufenthalts hatten als die Patient:innen im niederländischen Teil. Dies könnte auf sozioökonomische Faktoren oder eine unterschiedliche Organisation der ambulanten Gesundheitsversorgung zurückzuführen sein. Diese umfassende Studie zu MRSA, die Krankenhäuser über eine europäische Grenze hinweg abdeckt, hat gezeigt, dass eine routinemäßige MRSA-Surveillance hilfreich sein kann, um Trends von MRSA-Parametern zu überwachen, um (inter)nationale Vergleiche zu ermöglichen.

Die Diskussion dieser Studie schloss mit (übersetzt) „die grenzüberschreitende Überwachung sollte auf andere multiresistente Organismen ausgeweitet werden“, womit **Kapitel 10** fortgesetzt wird. Da nicht nur MRSA, sondern MDROs im Allgemeinen ein Risiko für die Gesundheitsversorgung darstellen, sowohl in der Allgemeinbevölkerung als auch in Krankenhäusern, zielte die Studie darauf ab, die Prävalenz mehrerer MDROs in dieser grenzüberschreitenden Region zu bestimmen, um Unterschiede zu verstehen und die Infektionsprävention auf der Grundlage von Echtzeit-Routinedaten und Arbeitsabläufen zu verbessern. Zu diesem Zweck nahmen 23 Krankenhäuser in der deutsch-niederländischen Grenzregion zwischen 2017 und 2018 an dieser prospektiven Studie teil, indem sie alle Patient:innen bei der Aufnahme auf Intensivstationen (ICUs) screenten. Alle Krankenhäuser (8 in den Niederlanden, 15 in Deutschland) nahmen für acht aufeinanderfolgende Wochen an der Studie teil und untersuchten die Patient:innen auf die Kolonisierung von MRSA, Vancomycin-resistenten Enterococcus faecium/E. faecalis (VRE), Cephalosporin-resistenten Enterobacteriaceae der dritten Generation (3GCRE) und Carbapenem-resistenten Enterobacteriaceae (CRE). Insgesamt wurden 3.365 Patient:innen gescreent: 36% auf niederländischen Intensivstationen und 64% auf deutschen Intensivstationen. Das mediane Alter aller gescreenten Patient:innen betrug 68 Jahre (IQR: 57-77), wobei die Patient:innen in der deutschen Grenzregion signifikant älter waren als die Patient:innen in der niederländischen Grenzregion. Die allgemeine Screening-Compliance (auf mindestens eine MDRO-Gruppe gescreent) lag bei 60%. Alle AMR-Datenanalysen wurden mit dem AMR-Paket für R durchgeführt und automatisiert. Die Prävalenz von MRSA betrug 1,7% in deutschen Intensivstationen und 0,6% in niederländischen Intensivstationen. Die Prävalenz von VRE betrug 2,7% in deutschen Intensivstationen und 0,1% in niederländischen Intensivstationen. Bemerkenswert ist, dass diese Prävalenz in der deutschen Grenzregion von 0% bis 4,1% reichte. Alle 56 Fälle von VRE wurden durch E. faecium verursacht. Die Prävalenz von 3GCRE betrug 6,6% in deutschen und 3,6% in niederländischen Intensivstationen, während die Prävalenz für CRE auf beiden Seiten der Grenze praktisch nicht präsent war. Die Prävalenz für gramnegative MDROs unterschied sich innerhalb beider Nationen zwischen den Krankenhäusern und reichte von 0% bis 5,0% in der niederländischen Grenzregion und von 1,2% bis 10,9% in der deutschen Grenzregion. Für die eingeschlossenen niederländischen Intensivstationen war die Prävalenz aller MDRO-Gruppen nicht signifikant unterschiedlich zwischen der nicht-universitären und der universitären Klinik. Für die deutschen Intensivstationen war jedoch die Prävalenz von gramnegativen MDROs in den nicht-universitären Krankenhäusern signifikant höher. In der niederländischen Grenzregion führten 4,8 von 100 Krankenhauseinweisungen zur Aufnahme auf der Intensivstation. Im Gegensatz dazu waren es in der deutschen Grenzregion 7,7 pro 100 Krankenhauseinweisungen. Dieser Unterschied lässt sich durch die höhere ICU-Kapazität in deutschen Krankenhäusern (4,8% aller Krankenhausbetten) im Vergleich zu niederländischen Krankenhäusern (2,4% aller Krankenhausbetten) erklären. Die Gesamtprävalenz für die verschiedenen MDROs war auf den deutschen Intensivstationen höher, obwohl einige Unterschiede marginal waren. Insbesondere war die Prävalenz von MRSA-Kolonisierung in der deutschen Grenzregion dreimal so hoch wie in der niederländischen Grenzregion, was mit den in **Kapitel 9** erwähnten Studienergebnissen übereinstimmt. Dennoch waren die Studienergebnisse nicht übereinstimmend mit (inter)nationalen Durchschnittswerten. Zum Beispiel war die Prävalenz der 3GCRE-Kolonisierung in der deutschen Grenzregion fast doppelt so hoch wie in der niederländischen Grenzregion, aber beide waren immer noch niedriger als der nationale Durchschnitt. Das ECDC meldete für Deutschland und die Niederlande 6% höhere 3GCRE-Anteile unter den Blutkulturisolaten von E. coli und K. pneumoniae. Dies unterstreicht, dass es wichtige Unterschiede gibt, wenn man die Kolonisierung in bestimmten Populationen untersucht und nicht den Anteil der (wahrscheinlich) invasiven Isolate betrachtet. Somit unterstreicht diese Studie die Bedeutung eines regionalen und grenzüberschreitenden Ansatzes in jeder europäischen grenzüberschreitenden Region, um die Unterschiede in der AMR-Prävalenz zwischen den Regionen zu verdeutlichen und mögliche Unterschiede zu landesweiten Berichten aufzuzeigen. Um dies weiter ausarbeiten zu können, ist ein tieferer Detaillierungsgrad erforderlich, z. B. durch die Erfassung von Informationen über das Personal auf den Stationen und das Personal der Infektionskontrolle, MDRO-Ausbrüche, Infektionen, Antibiotikaeinsatz und Risikofaktoren der Patient:innen. Zusammenfassend lässt sich sagen, dass geografische und politische Grenzen von MDROs anscheinend nicht „respektiert“ werden, obwohl die Gesundheitssysteme, die geografische Beschaffenheit und die Richtlinien in den einzelnen Nationen sehr unterschiedlich sind. Die Anteile von MDROs bestimmter Erreger, wie sie auf nationaler und internationaler Ebene berichtet werden, spiegeln nicht die MDRO-Prävalenz in der Patient:innen - oder Allgemeinbevölkerung wider. Dies sollte bei der Interpretation von Berichten auf Nationen - oder sogar Kontinentalebene ernsthaft in Betracht gezogen werden. 

**Fazit**

Das AMR-Paket und seine Vorteile werden aus verschiedenen Blickwinkeln betrachtet: aus technischer Sicht, aus der Sicht des Infektionsmanagements und aus klinischer Sicht. Diese Kombination bietet eine gemeinsame Grundlage für das Verständnis, was das AMR-Paket in der Praxis bewirken kann und wie es einen neuen, befähigten Ausgangspunkt für zukünftige Anwendungen der mikrobiellen Epidemiologie, sowohl in klinischen als auch in Forschungsumgebungen, setzen kann. Die vorliegende Dissertation vertieft diese vielfältigen Gesichtspunkte anschließend, indem sie den Einsatz dieses neuen Instruments in epidemiologischen Forschungsprojekten in der deutsch-niederländischen Grenzregion illustriert, um das Vorkommen und die AMR-Muster von Mikroorganismen auf (eu)regionaler Ebene besser zu verstehen. Zusammenfassend zeigt diese Dissertation den Mehrwert eines konsistenten datenanalytischen Instruments zur Aufbereitung und Analyse von AMR-Daten in einem flächendeckenden Ansatz, der auch im klinischen Umfeld eingesetzt werden kann, um neue Erkenntnisse über AMR-Muster zu erhalten.
